import type { CapacitorConfig } from "@capacitor/cli";

/**
 * Capacitor wraps the SAME web bundle (`dist/web`) that Cloudflare Pages serves, into a native
 * Android/iOS app. The one thing that changes between the web and the mobile shells is where the API
 * lives: the web app is served same-origin with the Worker (`/api/*` on kicklive.football), so it
 * talks to a relative `/api`. A mobile app is loaded from `https://localhost` (Android) or
 * `capacitor://localhost` (iOS) and therefore MUST call the deployed Worker by its absolute origin —
 * that origin is baked in at build time through `VITE_API_BASE_URL` (see `.env.mobile`, generated by
 * `scripts/build-web-env.mjs`), and the Worker's `ALLOWED_ORIGINS` must list the Capacitor origins or
 * every fetch fails CORS. Both halves of that contract are asserted by `npm run web:env:check`.
 */
const config: CapacitorConfig = {
  appId: "com.kicklive.app",
  appName: "KickLive",
  // The web build output. `npx cap sync` copies this tree into the native projects, so the app ships
  // the exact bytes Pages serves — build once with `npm run build:web:mobile`, then sync.
  webDir: "dist/web",
  // No `server.url`: the assets are bundled into the app, not loaded from a live URL. A live
  // `server.url` would turn the "native app" into a thin browser pointed at the website and break
  // offline start-up — the opposite of why a native shell exists.
  android: {
    // Android's WebView serves the bundle from https://localhost by default; keeping the scheme
    // https (not http) is what lets service-worker / secure-context features match the web shell.
    allowMixedContent: false,
  },
  ios: {
    // iOS serves from capacitor://localhost. Both origins are added to the Worker's ALLOWED_ORIGINS.
    contentInset: "always",
  },
};

export default config;
