#!/usr/bin/env node
/**
 * Writes the two Vite mode files `.env.staging` and `.env.production`, derived from
 * `workers/wrangler.toml` — the file that already carries these values, and the one the Worker is deployed from.
 *
 *   node scripts/build-web-env.mjs           # write both
 *   node scripts/build-web-env.mjs --check    # fail if either is stale (CI gate)
 *
 * WHY THIS EXISTS. A Pages deploy that succeeded and then served "KickLive is not configured" is the ordinary
 * outcome of `npm run build:web` run without `VITE_SUPABASE_URL`/`VITE_SUPABASE_ANON_KEY`: the build produces a
 * complete, working-looking bundle for a project that is not the app's backend, and nothing in the pipeline
 * objects. The boot guard in src/lib/env.ts is the last line and it does its job — but by then the artefact is
 * already deployed. The documented workaround (`VITE_… npm run build:web`) is worse than it looks: an inline
 * env pair is easy to omit on the second of two copy-pasted commands, and it *cannot* be enforced from a script.
 *
 * So the pair moves into Vite's own per-mode env files, and `npm run build:web:staging` /
 * `build:web:production` select one. That changes the failure from "silently unconfigured bundle" to "the mode
 * file is missing", which is a hard error before a single byte is written.
 *
 * WHY A GENERATOR AND NOT A COMMITTED KEY. `SUPABASE_ANON_KEY` per project already lives in
 * `workers/wrangler.toml` — correctly, because an anon key is public by Supabase's own threat model (RLS is the
 * enforcement layer, and the whole browser bundle is readable anyway). Writing the same value into a second
 * tracked file would create two places for it to drift apart, and drift between a URL and a key is precisely
 * the bug `env.ts` was introduced to catch. Deriving one from the other makes the drift impossible and makes
 * `--check` the thing that proves they still agree.
 *
 * WHAT IS NOT GENERATED. `VITE_API_BASE_URL` stays empty on purpose: the app talks to same-origin `/api`, which
 * the Vite dev proxy serves locally and Cloudflare serves directly once the custom domain routes `/api/*` to the
 * Worker. A per-environment API origin here would be a second routing decision, in a second place, to forget.
 */
import fs from "node:fs";
import path from "node:path";
import process from "node:process";

import { REPO_ROOT } from "../tools/vite-shared.ts";

const CONFIG = "workers/wrangler.toml";
const ENVS = ["staging", "production"];
const CHECK = process.argv.includes("--check");
const JSON_OUT = process.argv.includes("--json");

/** The one-bracket-per-line `[env.X.vars]` shape wrangler documents, and this repository uses. */
function varsFor(toml, env) {
  const header = `[env.${env}.vars]`;
  const at = toml.indexOf(header);
  if (at < 0) throw new Error(`${CONFIG}: no ${header} block`);
  const rest = toml.slice(at + header.length);
  const stop = rest.search(/^\s*\[/m);
  const block = stop < 0 ? rest : rest.slice(0, stop);
  const out = {};
  for (const m of block.matchAll(/^\s*([A-Z0-9_]+)\s*=\s*"([^"]*)"\s*$/gm)) out[m[1]] = m[2];
  return out;
}

function render(env, vars) {
  const url = vars.SUPABASE_URL;
  const key = vars.SUPABASE_ANON_KEY;
  const ref = vars.SUPABASE_PROJECT_REF;
  if (!url || !key || !ref) throw new Error(`${CONFIG}: [env.${env}.vars] is missing SUPABASE_URL / SUPABASE_ANON_KEY / SUPABASE_PROJECT_REF`);
  // The same assertion env.ts makes at boot, applied before the file exists at all: a key for another project
  // is a *valid looking* pair, which is why a build can ship it.
  const refFromUrl = /^https:\/\/([a-z0-9]+)\.supabase\.(co|in|dev)$/i.exec(url)?.[1];
  if (refFromUrl !== ref) throw new Error(`${CONFIG}: [env.${env}.vars] SUPABASE_URL parses to "${refFromUrl}" but SUPABASE_PROJECT_REF says "${ref}"`);
  return (
    `# GENERATED by scripts/build-web-env.mjs from ${CONFIG} [env.${env}.vars]. Do not edit — edit that file and re-run\n` +
    `# \`npm run web:env\`. \`npm run web:env:check\` fails CI if this drifts, so a Pages build can never again be the\n` +
    `# only place a project's identity is remembered.\n` +
    `#\n` +
    `# Selected by mode: \`npm run build:web:${env}\` → vite --mode ${env} → this file. A shell-provided VITE_* still\n` +
    `# wins (Vite reads process.env first), which is how the CI workflow keeps overriding it from GitHub Environments.\n` +
    `# The anon key is public by design (RLS is the enforcement layer); a service_role key must NEVER appear here.\n` +
    `VITE_SUPABASE_URL=${url}\n` +
    `VITE_SUPABASE_ANON_KEY=${key}\n` +
    `VITE_EXPECTED_PROJECT_REF=${ref}\n` +
    `VITE_API_BASE_URL=\n`
  );
}

const reports = [];
let stale = 0;
for (const env of ENVS) {
  const file = `.env.${env}`;
  const full = path.join(REPO_ROOT, file);
  let content;
  try {
    content = render(env, varsFor(fs.readFileSync(path.join(REPO_ROOT, CONFIG), "utf8"), env));
  } catch (e) {
    reports.push({ env, file, ok: false, error: e.message });
    stale++;
    continue;
  }
  const current = fs.existsSync(full) ? fs.readFileSync(full, "utf8") : null;
  if (CHECK) {
    const ok = current === content;
    if (!ok) stale++;
    reports.push({ env, file, ok, why: current === null ? "missing — run `npm run web:env`" : "stale — the Worker config changed since it was generated" });
  } else if (current !== content) {
    fs.writeFileSync(full, content);
    reports.push({ env, file, ok: true, written: true });
  } else {
    reports.push({ env, file, ok: true });
  }
}

if (JSON_OUT) {
  console.log(JSON.stringify({ check: CHECK, stale, reports }, null, 2));
} else {
  for (const r of reports) {
    const label = r.error ? `ERROR ${r.error}` : CHECK ? (r.ok ? "current" : r.why) : r.written ? "written" : "unchanged";
    console.log(`web-env: ${r.file.padEnd(16)} ${label}`);
  }
  if (CHECK && stale) {
    console.error(`web-env: ${stale} mode file(s) out of step with ${CONFIG} — run \`npm run web:env\` and commit the result`);
  }
}
process.exit(stale ? 1 : 0);
