#!/usr/bin/env node
/**
 * Bundle the Electron main + preload with esbuild into CommonJS under build/electron/.
 *
 * Why a bundler instead of shipping the TS sources: the packaged app must run with *zero*
 * node_modules (see electron-builder.yml `files`), and `electron` has to stay external so the
 * runtime resolves the real module from the Electron binary. The layout test asserts exactly that
 * (main.cjs contains `require("electron")` and no bundled Electron source).
 */

import fs from "node:fs";
import path from "node:path";
import process from "node:process";

import { REPO_ROOT, readVersionFile, writeFileEnsured } from "../tools/vite-shared.ts";
import { fmtSize } from "./lib/run.mjs";

const OUT_DIR = path.join(REPO_ROOT, "build", "electron");

export async function buildDesktop({ watch = false } = {}) {
  const { build, context } = await import("esbuild");
  const version = readVersionFile(REPO_ROOT);
  const shared = {
    absWorkingDir: REPO_ROOT,
    bundle: true,
    platform: "node",
    format: "cjs",
    target: ["node22"],
    external: ["electron"],
    sourcemap: false,
    minify: false,
    legalComments: "none",
    logLevel: "warning",
    define: {
      "process.env.NODE_ENV": JSON.stringify("production"),
      __BUILD_VERSION__: JSON.stringify(version),
    },
    banner: {
      js: `/* KickLive ${version} — generated by scripts/build-desktop.mjs, do not edit */`,
    },
  };

  fs.mkdirSync(OUT_DIR, { recursive: true });
  const entries = [
    { entry: "desktop/src/main.ts", outfile: path.join(OUT_DIR, "main.cjs") },
    { entry: "desktop/src/preload.ts", outfile: path.join(OUT_DIR, "preload.cjs") },
  ];

  if (watch) {
    for (const e of entries) {
      const ctx = await context({ ...shared, entryPoints: [path.join(REPO_ROOT, e.entry)], outfile: e.outfile });
      await ctx.watch();
      console.log(`build:desktop watching ${e.entry} → ${path.relative(REPO_ROOT, e.outfile)}`);
    }
    return { outDir: OUT_DIR, entries };
  }

  const results = [];
  for (const e of entries) {
    const meta = await build({ ...shared, entryPoints: [path.join(REPO_ROOT, e.entry)], outfile: e.outfile, metafile: true });
    const bytes = fs.statSync(e.outfile).size;
    const inputs = meta.metafile ? Object.keys(meta.metafile.inputs).length : 0;
    results.push({ entry: e.entry, outfile: path.relative(REPO_ROOT, e.outfile), bytes, inputs });
    console.log(`build:desktop ${e.entry} → ${path.relative(REPO_ROOT, e.outfile)} (${fmtSize(bytes)}, ${String(inputs)} modules)`);
  }
  const info = {
    product: "kicklive",
    version,
    generatedAt: new Date().toISOString(),
    entries: results,
    externals: ["electron"],
  };
  writeFileEnsured(path.join(OUT_DIR, "build-info.json"), JSON.stringify(info, null, 2) + "\n");
  verifyBundle(OUT_DIR);
  return { outDir: OUT_DIR, entries: results };
}

/** Cheap self-check so a mis-configured bundle fails at build time, not at `electron .` time. */
export function verifyBundle(dir = OUT_DIR) {
  const problems = [];
  const main = path.join(dir, "main.cjs");
  const preload = path.join(dir, "preload.cjs");
  for (const [label, file] of [
    ["main", main],
    ["preload", preload],
  ]) {
    if (!fs.existsSync(file)) {
      problems.push(`${label}: ${path.relative(REPO_ROOT, file)} was not produced`);
      continue;
    }
    const text = fs.readFileSync(file, "utf8");
    if (!text.includes('require("electron")') && !text.includes("require('electron')")) problems.push(`${label}: bundle does not reference the external electron module`);
    // Look for real ESM *statements* (line-initial), not the word "export" inside bundled code.
    const esm = /(^|\n)\s*(import\s*[{("]|export\s+(const|let|var|function|class|default|type)\b)/.exec(text);
    if (esm) problems.push(`${label}: ESM statement survived CJS bundling: ${JSON.stringify(esm[0].trim())}`);
    if (text.includes("import.meta.dirname")) problems.push(`${label}: import.meta.dirname in a CJS bundle is undefined at runtime`);
    if (/\bawait\s+import\("electron"\)/.test(text)) problems.push(`${label}: dynamic electron import defeats the sandbox preload`);
  }
  if (problems.length > 0) throw new Error(`build:desktop bundle check failed:\n  - ${problems.join("\n  - ")}`);
  return true;
}

if (process.argv[1] && path.resolve(process.argv[1]).endsWith("build-desktop.mjs")) {
  await buildDesktop({ watch: process.argv.includes("--watch") });
}
