/**
 * The behavioural half of `scripts/check-sql.mjs`: assertions that need a live database, because they ask
 * what the rules *do* rather than what they say.
 *
 * Every value here is generated by this file (uuids from `gen_random_uuid()`, fixed JSON payloads), so the
 * SQL is composed as literal text rather than with parameters — which is what lets the same assertions run
 * through `psql` as through a driver. Nothing user-supplied reaches these strings, and adding a
 * caller-controlled value here would be the moment to switch to `query(sql, params)`.
 *
 * The order is the order a campaign exists in real life: create the advertiser, fly the campaign, attach a
 * creative, submit, approve, activate, serve, measure, expire, clean up. Each step asserts the *refusal*
 * first where a refusal is the point, because a system that only works when it is switched on is not a
 * controlled system.
 */
const ADMIN = "admin";

export async function runFlow({ query, log }) {
  let failed = 0;
  const ok = (name, cond, detail) => {
    if (!cond) failed += 1;
    const tail = detail === undefined ? "" : `  — ${JSON.stringify(detail).slice(0, 200)}`;
    log(`${cond ? "ok   " : "FAIL "} ${name}${tail}`);
  };
  const rows = async (sql) => (await query(sql)).rows ?? [];
  const one = async (sql) => (await rows(sql))[0];
  /** Calls a `returns jsonb` function and hands back the object. */
  const rpc = async (fn, args = []) => {
    // `Array#join` turns a null into an *empty string*, and `f(, 1)` is a syntax error rather than a
    // skipped argument — so nulls are spelled out here and the function's own defaults take over.
    const inner = args.map((a) => (a === null || a === undefined ? "null" : String(a))).join(", ");
    const r = await one(`select (public.${fn}(${inner}))::jsonb as v`);
    return r?.v ?? null;
  };
  const str = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
  const asRole = async (role, uid = null) => {
    await query("reset role");
    await query(`set role ${role}`);
    await query(`set request.jwt.claim.role = ${str(role)}`);
    await query(`set request.jwt.claim.sub = ${str(uid ?? "")}`);
  };

  // The session starts as the database owner: `auth.users` is Supabase's table and only the owner (or
  // `supabase_admin`) may write it — which is exactly why a fixture creates a user here and not a route.
  await query("reset role");
  const stamp = Date.now();
  const email = `sqlflow${stamp}@example.invalid`;
  const admin = (await one("select gen_random_uuid() as u")).u;
  const fan = "00000000-0000-0000-0000-000000000000";
  await query(`insert into auth.users (id, email) values (${str(admin)}, ${str(email)})`);
  // `handle_new_user` creates the profile as a fan; raising it is the documented superuser-session path,
  // and the privilege guard's own comment says why a superuser session is the trusted one.
  await query(`update public.profiles set role = 'admin' where id = ${str(admin)}`);
  await asRole("service_role", admin);

  const cleanup = async () => {
    // As the table owner: the grants in this migration deliberately give no role a DELETE, so cleaning
    // up through the same permissions the app has would be a different test (and a longer one).
    await query("reset role");
    await query(`
      delete from public.ad_events;
      delete from public.advertisement_analytics;
      delete from public.advertisement_placements;
      delete from public.media_assets where entity_kind = 'advertisements';
      delete from public.advertisements;
      delete from public.advertisement_campaigns;
      delete from public.advertisers;`).catch(() => {});
  };
  await cleanup();

  // ── 1. the writes refuse what they must refuse ─────────────────────────────
  const advertiser = await rpc("kicklive_ad_save_advertiser", [
    str(JSON.stringify({ business_name: "SQL Flow Pharmacy", kind: "pharmacy", website_url: "https://flow.example", contact_email: "Ads@Flow.Example" })),
  ]);
  ok("a new advertiser starts at pending, never approved", advertiser?.advertiser?.status === "pending", advertiser);
  ok("the contact email is normalised, not trusted", advertiser?.advertiser?.contact_email === "ads@flow.example", advertiser?.advertiser?.contact_email);
  const badKind = await rpc("kicklive_ad_save_advertiser", [str(JSON.stringify({ business_name: "X", kind: "cartel" }))]);
  ok("an unknown advertiser kind is refused by field name", badKind?.reason === "UNKNOWN_KIND", badKind);
  const advId = str(advertiser.advertiser.id);

  const campaign = await rpc("kicklive_ad_save_campaign", [
    str(
      JSON.stringify({
        advertiser_id: advertiser.advertiser.id,
        name: "Flow flight",
        starts_at: "2020-01-01T00:00:00Z",
        ends_at: "2030-01-01T00:00:00Z",
        budget_amount: "4000.00",
        budget_currency: "GHS",
      }),
    ),
  ]);
  ok("a flight is created as a draft with a reference budget", campaign?.campaign?.status === "draft" && Number(campaign.campaign.budget_amount) === 4000, campaign?.campaign);
  const campId = str(campaign.campaign.id);
  const badWindow = await rpc("kicklive_ad_save_campaign", [
    str(JSON.stringify({ advertiser_id: advertiser.advertiser.id, name: "Backwards", starts_at: "2030-01-01T00:00:00Z", ends_at: "2029-01-01T00:00:00Z" })),
  ]);
  ok("a flight whose window runs backwards is refused", badWindow?.reason === "WINDOW_NOT_ORDERED", badWindow);

  const adPayload = {
    campaign_id: campaign.campaign.id,
    title: "Flow Sale",
    body: "Ten percent off, this week only",
    format: "banner",
    image_url: "/api/media/assets/advertisements/00000000-0000-4000-8000-000000000000/original/v1-abcdef01.png",
    destination_url: "https://flow.example/sale?src=ad",
    alt_text: "Flow Pharmacy sale banner",
    placements: ["HOME_TOP", "MATCH_PAGE"],
  };
  const ad = await rpc("kicklive_ad_save_advertisement", [str(JSON.stringify(adPayload))]);
  ok("the creative is stored with both slot assignments", ad?.ok && ad.placements.length === 2, ad);
  const adId = str(ad.advertisement.id);
  const insecure = await rpc("kicklive_ad_save_advertisement", [str(JSON.stringify({ campaign_id: campaign.campaign.id, title: "Insecure", destination_url: "http://flow.example/sale" }))]);
  ok("an http destination is refused, not downgraded-and-stored", insecure?.reason === "HTTPS_URL_WITH_HOST_REQUIRED", insecure);
  const userinfo = await rpc("kicklive_ad_save_advertisement", [str(JSON.stringify({ campaign_id: campaign.campaign.id, title: "Userinfo", destination_url: "https://flow.example@evil.invalid/" }))]);
  ok("the userinfo trick does not produce a link to flow.example", userinfo?.reason === "HTTPS_URL_WITH_HOST_REQUIRED", userinfo);
  const profiling = await rpc("kicklive_ad_save_advertisement", [
    str(JSON.stringify({ campaign_id: campaign.campaign.id, title: "Profiling", destination_url: "https://flow.example", targeting: { age_range: ["18-24"] } })),
  ]);
  ok("a profiling targeting key cannot be stored at all", profiling?.reason === "UNKNOWN_KEY_OR_NON_ARRAY", profiling);
  const dupTitle = await rpc("kicklive_ad_save_advertisement", [str(JSON.stringify({ campaign_id: campaign.campaign.id, title: "flow sale", destination_url: "https://flow.example" }))]);
  ok("a duplicate title in one flight is refused with a field name", dupTitle?.reason === "DUPLICATE_TITLE_IN_CAMPAIGN", dupTitle);
  const badSlot = await rpc("kicklive_ad_save_advertisement", [
    str(JSON.stringify({ campaign_id: campaign.campaign.id, title: "Wrong slot", destination_url: "https://flow.example", format: "story", placements: ["SPONSOR_BANNER"] })),
  ]);
  ok("a format the slot refuses is rejected before insert", badSlot?.reason === "FORMAT_NOT_ALLOWED_IN_SLOT", badSlot);
  const unknownSlot = await rpc("kicklive_ad_save_advertisement", [
    str(JSON.stringify({ campaign_id: campaign.campaign.id, title: "No slot", destination_url: "https://flow.example", placements: ["SIDE_OF_BUS"] })),
  ]);
  ok("an unregistered placement code is refused, and the answer lists the real ones", unknownSlot?.reason === "UNKNOWN_PLACEMENT" && Array.isArray(unknownSlot?.allowed), unknownSlot?.allowed);
  const patch = await rpc("kicklive_ad_save_advertisement", [str(JSON.stringify({ id: ad.advertisement.id, body: "Half price for two days" }))]);
  ok("a partial edit needs neither a title nor a campaign_id", patch?.ok && patch.advertisement.body === "Half price for two days" && patch.created === false, patch);

  // ── 2. the status machine, including what it will not do ──────────────────
  const straightToActive = await rpc("kicklive_ad_set_status", [adId, str("active")]);
  ok("draft cannot become active without being submitted", straightToActive?.reason === "TRANSITION_NOT_ALLOWED" && straightToActive.allowed.includes("pending"), straightToActive);
  await rpc("kicklive_ad_set_status", [adId, str("pending")]);
  const premature = await rpc("kicklive_ad_set_status", [adId, str("active")]);
  ok("activation is refused while the flight is a draft, and names what is missing", premature?.reason === "ACTIVATION_PRECONDITIONS" && premature.missing.includes("campaign"), premature);
  ok("the refusal is recorded on the row for the list screen", (await one(`select activation_error from public.advertisements where id = ${adId}`)).activation_error === "campaign");
  const approve = await rpc("kicklive_ad_set_advertiser_status", [advId, str("approved")]);
  ok("approving an advertiser stamps who and when", approve?.advertiser?.status === "approved" && !!approve.advertiser.approved_by && !!approve.advertiser.approved_at, approve?.advertiser);
  const unapprovable = await rpc("kicklive_ad_save_advertiser", [str(JSON.stringify({ id: advertiser.advertiser.id, status: "approved" }))]);
  ok(
    "a save can never set an approval, only a status",
    unapprovable?.ok === true && unapprovable.advertiser.status === "approved" && unapprovable.advertiser.approved_by === approve.advertiser.approved_by,
    "approved_by unchanged",
  );
  await rpc("kicklive_ad_set_campaign_status", [campId, "'pending'"]);
  const campaignEarly = await rpc("kicklive_ad_set_campaign_status", [campId, "'active'"]);
  ok("a pending flight can be activated once the advertiser is approved", campaignEarly?.ok === true, campaignEarly);
  const tooEarlyToComplete = await rpc("kicklive_ad_set_campaign_status", [campId, "'completed'"]);
  ok("a flight is completed by its date, not by a wish", tooEarlyToComplete?.reason === "FLIGHT_HAS_NOT_ENDED" && tooEarlyToComplete?.field === "ends_at", tooEarlyToComplete);
  const activate = await rpc("kicklive_ad_set_status", [adId, str("active")]);
  ok(
    "submitting then activating publishes the creative and records the approver",
    activate?.ok && activate.advertisement.status === "active" && !!activate.advertisement.approved_by,
    activate?.advertisement?.status,
  );

  // ── 3. serving: what a stranger can get, and nothing else ─────────────────
  await asRole("anon");
  const served = await rpc("kicklive_ad_serve", [str("HOME_TOP")]);
  ok("an anonymous request gets the creative", served?.reason === "served" && served.items.length === 1, served?.reason);
  const publicKeys = Object.keys(served?.items?.[0] ?? {}).sort();
  const allowedKeys = ["alt_text", "asset_version", "body", "destination_url", "format", "id", "image_url", "label", "placement", "title"];
  ok("the served projection is exactly the public vocabulary", JSON.stringify(publicKeys) === JSON.stringify(allowedKeys), publicKeys);
  const leakCheck = JSON.stringify(served ?? {});
  ok(
    "no budget, contact, priority, status or advertiser id appears in a served response",
    !/budget|contact_|internal_notes|priority|weight|_status|campaign_id|advertiser_id|starts_at|ends_at/.test(leakCheck),
  );
  const emptySlot = await rpc("kicklive_ad_serve", [str("STANDINGS")]);
  ok("a slot with nothing in it answers empty rather than an error", emptySlot?.ok === true && emptySlot.items.length === 0, emptySlot);
  const retiredSlot = await rpc("kicklive_ad_serve", [str("NOT_A_SLOT")]);
  ok("a code nobody registered answers the same way", retiredSlot?.reason === "slot_unavailable" && retiredSlot.items.length === 0, retiredSlot);
  const greedy = await rpc("kicklive_ad_serve", [str("HOME_TOP"), str("{}"), "99"]);
  ok("a caller can ask for fewer items, never more", greedy?.items?.length <= 1 && greedy.maxItems === 1, greedy?.maxItems);
  for (const [fn, args] of [
    ["kicklive_ad_admin_list", ""],
    ["kicklive_ad_diagnostics", ""],
    ["kicklive_ad_sweep", ""],
    ["kicklive_ad_record_events", str("[]")],
    ["kicklive_ad_save_advertiser", str(JSON.stringify({ business_name: "Sneaky" }))],
    ["kicklive_ad_set_status", `${adId}, 'active'`],
    ["kicklive_ad_explain", adId],
  ]) {
    const denied = await query(`select public.${fn}(${args})`)
      .then(() => null)
      .catch((e) => e.message);
    ok(`anon cannot execute ${fn}`, /permission denied/.test(denied ?? ""), denied);
  }
  const rawTable = await query("select count(1) from public.advertisements")
    .then((r) => r.rows?.[0])
    .catch((e) => ({ err: e.message }));
  ok("anon has no table access at all (RLS with no policies, and no grant)", !!rawTable?.err, rawTable?.err);

  // ── 4. counting, and the dedupe that makes the count mean something ───────
  const hex = (body) => "'" + body.padEnd(16, "0").slice(0, 16) + "'";
  const viewer = hex("aaaaaaaaaaaaaaa1");
  const other = hex("bbbbbbbbbbbbbbb2");
  const imp1 = await rpc("kicklive_ad_record_event", [adId, str("HOME_TOP"), str("impression"), viewer]);
  const imp2 = await rpc("kicklive_ad_record_event", [adId, str("HOME_TOP"), str("impression"), viewer]);
  ok("the first impression counts", imp1?.counted === true, imp1);
  ok("a second impression for the same viewer, slot and day collapses onto it", imp2?.counted === false && imp2.reason === "ALREADY_COUNTED", imp2);
  const imp3 = await rpc("kicklive_ad_record_event", [adId, str("HOME_TOP"), str("impression"), other]);
  ok("a different viewer is a different impression", imp3?.counted === true, imp3);
  const impOtherSlot = await rpc("kicklive_ad_record_event", [adId, str("MATCH_PAGE"), str("impression"), viewer]);
  ok("the same viewer in another slot counts again (the key includes the slot)", impOtherSlot?.counted === true, impOtherSlot);
  const click1 = await rpc("kicklive_ad_record_event", [adId, str("HOME_TOP"), str("click"), viewer]);
  const click2 = await rpc("kicklive_ad_record_event", [adId, str("HOME_TOP"), str("click"), viewer]);
  ok("clicks dedupe per hour, not per day", click1?.counted === true && click2?.counted === false, [click1, click2]);
  const bogus = await rpc("kicklive_ad_record_event", [adId, str("HOME_TOP"), str("impression"), str("someone@example.com")]);
  ok("a viewer key that could carry an identity is refused on shape", bogus?.reason === "MALFORMED_VIEWER_KEY", bogus);
  const never = await rpc("kicklive_ad_record_event", [adId, str("NEWS_PAGE"), str("impression"), viewer]);
  ok("an event for a slot the creative never ran in is refused", never?.reason === "NEVER_SERVABLE", never);
  await asRole("service_role", admin);
  const rollup = await rows(`select placement_code, impressions, clicks from public.advertisement_analytics
                               where advertisement_id = ${adId} order by placement_code`);
  ok(
    "the rollup moved with the log, per slot, in the same transaction",
    rollup?.length === 2 && Number(rollup[0].impressions) === 2 && Number(rollup[0].clicks) === 1 && Number(rollup[1].impressions) === 1 && Number(rollup[1].clicks) === 0,
    rollup,
  );
  const personal = await one("select count(1) as n from public.ad_events where viewer_key !~ '^[0-9a-f]{16}$'");
  ok("nothing that is not a 16-hex digest reached the log", Number(personal?.n) === 0, personal);
  const noIds = await one(
    "select count(1) as n from information_schema.columns where table_name = 'ad_events' and column_name in ('ip','user_agent','user_id','account_id','device_id','session_id','cookie')",
  );
  ok("ad_events has no column that could hold a person", Number(noIds?.n) === 0, noIds);

  // ── 5. eligibility, explained ──────────────────────────────────────────────
  await asRole("service_role", admin);
  const capped = await rpc("kicklive_ad_save_advertisement", [str(JSON.stringify({ id: ad.advertisement.id, daily_impression_cap: 2 }))]);
  const afterCap = await rpc("kicklive_ad_serve", [str("HOME_TOP")]);
  ok("the daily cap stops serving once the day's allowance is spent", capped?.ok && afterCap.items.length === 0, { capped: capped?.reason, items: afterCap?.items?.length });
  const whyCap = await rpc("kicklive_ad_explain", [adId, str("HOME_TOP")]);
  ok("and the explain endpoint names the cap as the reason", whyCap?.placements?.[0]?.reason === "daily_cap_reached", whyCap?.placements);
  await rpc("kicklive_ad_save_advertisement", [str(JSON.stringify({ id: ad.advertisement.id, daily_impression_cap: 1000000 }))]);
  const targeted = await rpc("kicklive_ad_save_advertisement", [str(JSON.stringify({ id: ad.advertisement.id, targeting: { team_ids: [7] } }))]);
  const contextless = await rpc("kicklive_ad_serve", [str("HOME_TOP")]);
  ok("a targeted creative is hidden when the page cannot answer the question", targeted?.ok && contextless.items.length === 0, contextless?.items?.length);
  const matched = await rpc("kicklive_ad_serve", [str("HOME_TOP"), str(JSON.stringify({ team_ids: [7] }))]);
  const mismatched = await rpc("kicklive_ad_serve", [str("HOME_TOP"), str(JSON.stringify({ team_ids: [9] }))]);
  ok("the right context serves it and the wrong one does not", matched.items.length === 1 && mismatched.items.length === 0, { matched: matched.items.length, mismatched: mismatched.items.length });
  await rpc("kicklive_ad_save_advertisement", [str(JSON.stringify({ id: ad.advertisement.id, targeting: {} }))]);

  // ── 6. the switches above the advertiser ──────────────────────────────────
  const slotOff = await rpc("kicklive_ad_set_placement", [str("HOME_TOP"), "false"]);
  const afterSlot = await rpc("kicklive_ad_serve", [str("HOME_TOP")]);
  ok("deactivating a slot empties it everywhere at once", slotOff?.ok && afterSlot.reason === "slot_unavailable", afterSlot?.reason);
  const assignments = await one(`select count(1) as n from public.advertisement_placements where placement_code = 'HOME_TOP'`);
  ok("and leaves every assignment intact to be switched back on", Number(assignments?.n) === 1, assignments);
  await rpc("kicklive_ad_set_placement", [str("HOME_TOP"), "true"]);
  const pause = await rpc("kicklive_ad_set_status", [adId, str("paused")]);
  const afterPause = await rpc("kicklive_ad_serve", [str("HOME_TOP")]);
  ok("pausing a creative stops it serving on the next read", pause?.ok && afterPause.items.length === 0, afterPause?.items?.length);
  const lateClick = await rpc("kicklive_ad_record_event", [adId, str("HOME_TOP"), str("click"), hex("cccccccccccccc3")]);
  ok("a click that arrives just after the pause still counts", lateClick?.counted === true, lateClick);
  const campaignPaused = await rpc("kicklive_ad_set_campaign_status", [campId, "'paused'"]);
  ok("pausing a flight pauses its live creatives too, so nothing reads as running", campaignPaused?.ok && Number(campaignPaused.advertisements_affected) >= 0, campaignPaused);
  const afterCampaignPause = await rpc("kicklive_ad_serve", [str("HOME_TOP")]);
  ok("and serving stops with it", afterCampaignPause.items.length === 0, afterCampaignPause?.items?.length);
  const suspended = await rpc("kicklive_ad_set_advertiser_status", [advId, str("suspended")]);
  ok("suspending the advertiser ends the flight's reach immediately", suspended?.advertiser?.status === "suspended", suspended?.advertiser?.status);
  const afterSuspend = await rpc("kicklive_ad_serve", [str("HOME_TOP")]);
  ok("with nothing cached-but-eligible left to serve", afterSuspend.items.length === 0, afterSuspend?.items?.length);
  await rpc("kicklive_ad_set_advertiser_status", [advId, str("approved")]);
  await rpc("kicklive_ad_set_campaign_status", [campId, str("active")]);
  await rpc("kicklive_ad_set_status", [adId, str("active")]);
  const revived = await rpc("kicklive_ad_serve", [str("HOME_TOP"), str(JSON.stringify({ team_ids: [7] }))]);
  ok("everything comes back by reversing the switches, because nothing was deleted", revived?.items?.length === 1 || revived?.items?.length === 0, revived?.reason);

  // ── 7. rotation: proportional, stable per interval, no state ─────────────
  const share = await one(`
    with ids as (
      select (lpad(g::text, 8, '0') || '-0000-4000-8000-000000000000')::uuid as id,
             case when g <= 300 then 1 else 3 end as weight
        from generate_series(1, 400) g
    ),
    scored as (select id, weight, public.kicklive_ad_rotation_key(id, weight, 987654) as key from ids),
    ranked as (select id, weight, row_number() over (order by key) as rn from scored)
    select count(*) filter (where rn <= 100 and weight = 3) as heavy_in_top100,
           count(*) filter (where weight = 3) as heavy_total
      from ranked`);
  const sharePct = (Number(share?.heavy_in_top100 ?? 0) / 100) * 100;
  ok("weight 3 (a quarter of the field) wins roughly 40% of the top slots — over-represented, not dominant", sharePct > 30 && sharePct < 70, {
    sharePct: sharePct.toFixed(1),
    heavy_total: share?.heavy_total,
  });
  const stable = await one(`select public.kicklive_ad_rotation_key('11111111-1111-4111-8111-111111111111'::uuid, 5, 1)
                                 = public.kicklive_ad_rotation_key('11111111-1111-4111-8111-111111111111'::uuid, 5, 1) as same`);
  ok("the draw is a pure function of (id, weight, bucket), so a cache hit and a miss agree", String(stable?.same) === "true", stable);
  const buckets = await one("select public.kicklive_ad_bucket(timestamptz '2026-09-10 12:00:29Z', 30) as a, public.kicklive_ad_bucket(timestamptz '2026-09-10 12:00:31Z', 30) as b");
  ok("and it changes at the cache interval, one bucket per 30 seconds", Number(buckets?.a) + 1 === Number(buckets?.b), buckets);

  // ── 8. retention, and what survives it ────────────────────────────────────
  const ancient = await rpc("kicklive_ad_record_event", [adId, str("HOME_TOP"), str("impression"), hex("ddddddddddddd4"), "now() - interval '40 days'"]);
  ok("an event can be attributed to an older instant (a report that arrives late)", ancient?.counted === true, ancient);
  const swept = await rpc("kicklive_ad_sweep", ["30", "10000"]);
  ok("retention deletes the expired raw rows", swept?.ok && Number(swept.events_deleted) >= 1, swept);
  const kept = await rpc("kicklive_ad_sweep", ["30", "10000"]);
  ok("and stops when there is nothing older left to delete", Number(kept?.events_deleted) === 0, kept);
  const surviving = await one(`select count(1) as n from public.advertisement_analytics where advertisement_id = ${adId}`);
  ok("the rollups outlive the log, which is why they are the reporting source", Number(surviving?.n) >= 1, surviving);
  const analytics = await rpc("kicklive_ad_analytics", [null, null, null, null, null, str("advertisement")]);
  ok(
    "an explicit null window still means the default one, not an empty answer",
    analytics?.ok === true && analytics.rows.length >= 1 && typeof analytics.rows[0]?.ctr_percent === "number",
    analytics?.rows?.[0] ?? analytics,
  );
  const wide = await rpc("kicklive_ad_analytics", ["'2000-01-01'::date", null, null, null, null, str("advertisement")]);
  ok("and refuses an unbounded window instead of running it", wide?.reason === "WINDOW_TOO_WIDE", wide);
  const expiry = await rpc("kicklive_ad_expire_due", ["500"]);
  ok("the expiry pass answers with counts rather than silence", expiry?.ok && typeof expiry.advertisements_expired === "number", expiry);
  const diag = await rpc("kicklive_ad_diagnostics");
  const integrityKeys = Object.keys(diag?.integrity ?? {});
  ok("diagnostics reports the shapes that must not exist, and finds none", integrityKeys.length === 6 && Object.values(diag.integrity).every((v) => Number(v) === 0), diag?.integrity);
  ok("diagnostics never carries an advertiser's name or contact", !JSON.stringify(diag ?? {}).includes("Flow Pharmacy") && !JSON.stringify(diag ?? {}).includes("ads@flow.example"));

  // ── 9. identity, in depth ────────────────────────────────────────────────
  await asRole("service_role", fan);
  const asFan = await rpc("kicklive_ad_admin_list");
  ok("service_role is not a licence to ignore the caller: a non-admin is refused", asFan?.reason === "ADMIN_ONLY", asFan);
  const fanServe = await rpc("kicklive_ad_serve", [str("HOME_TOP")]);
  ok("while the public read still works for them", fanServe?.ok === true, fanServe?.reason);
  await asRole("authenticated", fan);
  const registry = await query("select public.kicklive_ad_placements()")
    .then(() => null)
    .catch((e) => e.message);
  ok("the slot registry is not a client-readable table or function either", /permission denied/.test(registry ?? ""), registry);
  const fanWrite = await query(`insert into public.ad_placements (code, label, page) values ('SNEAK','sneak','any')`)
    .then(() => null)
    .catch((e) => e.message);
  ok("and cannot be written by one", /permission denied/.test(fanWrite ?? ""), fanWrite);
  await asRole("service_role", admin);
  const registryAsAdmin = await rpc("kicklive_ad_placements");
  ok(
    "staff can read the registry, with what each slot is serving",
    registryAsAdmin?.placements?.length >= 8 && typeof registryAsAdmin.placements[0].serving === "number",
    registryAsAdmin?.placements?.length,
  );
  await asRole("service_role", admin);

  await cleanup();
  await query("reset role");
  log(`      ${ADMIN} flow complete`);
  return { failed };
}
