/**
 * The behavioural half of `scripts/check-sql.mjs`: assertions that need a live database, because they ask
 * what the rules *do* rather than what they say.
 *
 * Every value here is generated by this file (uuids from `gen_random_uuid()`, fixed JSON payloads), so the
 * SQL is composed as literal text rather than with parameters — which is what lets the same assertions run
 * through `psql` as through a driver. Nothing user-supplied reaches these strings, and adding a
 * caller-controlled value here would be the moment to switch to `query(sql, params)`.
 *
 * The order is the order a campaign exists in real life: create the advertiser, fly the campaign, attach a
 * creative, submit, approve, activate, serve, measure, expire, clean up. Each step asserts the *refusal*
 * first where a refusal is the point, because a system that only works when it is switched on is not a
 * controlled system.
 */
const ADMIN = "admin";

export async function runFlow({ query, log }) {
  let failed = 0;
  const ok = (name, cond, detail) => {
    if (!cond) failed += 1;
    const tail = detail === undefined ? "" : `  — ${JSON.stringify(detail).slice(0, 200)}`;
    log(`${cond ? "ok   " : "FAIL "} ${name}${tail}`);
  };
  const rows = async (sql) => (await query(sql)).rows ?? [];
  const one = async (sql) => (await rows(sql))[0];
  /** Calls a `returns jsonb` function and hands back the object. */
  const rpc = async (fn, args = []) => {
    // `Array#join` turns a null into an *empty string*, and `f(, 1)` is a syntax error rather than a
    // skipped argument — so nulls are spelled out here and the function's own defaults take over.
    const inner = args.map((a) => (a === null || a === undefined ? "null" : String(a))).join(", ");
    const r = await one(`select (public.${fn}(${inner}))::jsonb as v`);
    return r?.v ?? null;
  };
  const str = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
  const asRole = async (role, uid = null) => {
    await query("reset role");
    await query(`set role ${role}`);
    await query(`set request.jwt.claim.role = ${str(role)}`);
    await query(`set request.jwt.claim.sub = ${str(uid ?? "")}`);
  };

  // The session starts as the database owner: `auth.users` is Supabase's table and only the owner (or
  // `supabase_admin`) may write it — which is exactly why a fixture creates a user here and not a route.
  await query("reset role");
  const stamp = Date.now();
  const email = `sqlflow${stamp}@example.invalid`;
  const admin = (await one("select gen_random_uuid() as u")).u;
  const fan = "00000000-0000-0000-0000-000000000000";
  await query(`insert into auth.users (id, email) values (${str(admin)}, ${str(email)})`);
  // `handle_new_user` creates the profile as a fan; raising it is the documented superuser-session path,
  // and the privilege guard's own comment says why a superuser session is the trusted one.
  await query(`update public.profiles set role = 'admin' where id = ${str(admin)}`);
  await asRole("service_role", admin);

  const cleanup = async () => {
    // As the table owner: the grants in this migration deliberately give no role a DELETE, so cleaning
    // up through the same permissions the app has would be a different test (and a longer one).
    await query("reset role");
    await query(`
      delete from public.ad_events;
      delete from public.advertisement_analytics;
      delete from public.advertisement_placements;
      delete from public.media_assets where entity_kind = 'advertisements';
      delete from public.advertisements;
      delete from public.advertisement_campaigns;
      delete from public.advertisers;`).catch(() => {});
  };
  await cleanup();

  // ── 1. the writes refuse what they must refuse ─────────────────────────────
  const advertiser = await rpc("kicklive_ad_save_advertiser", [
    str(JSON.stringify({ business_name: "SQL Flow Pharmacy", kind: "pharmacy", website_url: "https://flow.example", contact_email: "Ads@Flow.Example" })),
  ]);
  ok("a new advertiser starts at pending, never approved", advertiser?.advertiser?.status === "pending", advertiser);
  ok("the contact email is normalised, not trusted", advertiser?.advertiser?.contact_email === "ads@flow.example", advertiser?.advertiser?.contact_email);
  const badKind = await rpc("kicklive_ad_save_advertiser", [str(JSON.stringify({ business_name: "X", kind: "cartel" }))]);
  ok("an unknown advertiser kind is refused by field name", badKind?.reason === "UNKNOWN_KIND", badKind);
  const advId = str(advertiser.advertiser.id);

  const campaign = await rpc("kicklive_ad_save_campaign", [
    str(
      JSON.stringify({
        advertiser_id: advertiser.advertiser.id,
        name: "Flow flight",
        starts_at: "2020-01-01T00:00:00Z",
        ends_at: "2030-01-01T00:00:00Z",
        budget_amount: "4000.00",
        budget_currency: "GHS",
      }),
    ),
  ]);
  ok("a flight is created as a draft with a reference budget", campaign?.campaign?.status === "draft" && Number(campaign.campaign.budget_amount) === 4000, campaign?.campaign);
  const campId = str(campaign.campaign.id);
  const badWindow = await rpc("kicklive_ad_save_campaign", [
    str(JSON.stringify({ advertiser_id: advertiser.advertiser.id, name: "Backwards", starts_at: "2030-01-01T00:00:00Z", ends_at: "2029-01-01T00:00:00Z" })),
  ]);
  ok("a flight whose window runs backwards is refused", badWindow?.reason === "WINDOW_NOT_ORDERED", badWindow);

  const adPayload = {
    campaign_id: campaign.campaign.id,
    title: "Flow Sale",
    body: "Ten percent off, this week only",
    format: "banner",
    image_url: "/api/media/assets/advertisements/00000000-0000-4000-8000-000000000000/original/v1-abcdef01.png",
    destination_url: "https://flow.example/sale?src=ad",
    alt_text: "Flow Pharmacy sale banner",
    placements: ["HOME_TOP", "MATCH_PAGE"],
  };
  const ad = await rpc("kicklive_ad_save_advertisement", [str(JSON.stringify(adPayload))]);
  ok("the creative is stored with both slot assignments", ad?.ok && ad.placements.length === 2, ad);
  const adId = str(ad.advertisement.id);
  const insecure = await rpc("kicklive_ad_save_advertisement", [str(JSON.stringify({ campaign_id: campaign.campaign.id, title: "Insecure", destination_url: "http://flow.example/sale" }))]);
  ok("an http destination is refused, not downgraded-and-stored", insecure?.reason === "HTTPS_URL_WITH_HOST_REQUIRED", insecure);
  const userinfo = await rpc("kicklive_ad_save_advertisement", [str(JSON.stringify({ campaign_id: campaign.campaign.id, title: "Userinfo", destination_url: "https://flow.example@evil.invalid/" }))]);
  ok("the userinfo trick does not produce a link to flow.example", userinfo?.reason === "HTTPS_URL_WITH_HOST_REQUIRED", userinfo);
  const profiling = await rpc("kicklive_ad_save_advertisement", [
    str(JSON.stringify({ campaign_id: campaign.campaign.id, title: "Profiling", destination_url: "https://flow.example", targeting: { age_range: ["18-24"] } })),
  ]);
  ok("a profiling targeting key cannot be stored at all", profiling?.reason === "UNKNOWN_KEY_OR_NON_ARRAY", profiling);
  const dupTitle = await rpc("kicklive_ad_save_advertisement", [str(JSON.stringify({ campaign_id: campaign.campaign.id, title: "flow sale", destination_url: "https://flow.example" }))]);
  ok("a duplicate title in one flight is refused with a field name", dupTitle?.reason === "DUPLICATE_TITLE_IN_CAMPAIGN", dupTitle);
  const badSlot = await rpc("kicklive_ad_save_advertisement", [
    str(JSON.stringify({ campaign_id: campaign.campaign.id, title: "Wrong slot", destination_url: "https://flow.example", format: "story", placements: ["SPONSOR_BANNER"] })),
  ]);
  ok("a format the slot refuses is rejected before insert", badSlot?.reason === "FORMAT_NOT_ALLOWED_IN_SLOT", badSlot);
  const unknownSlot = await rpc("kicklive_ad_save_advertisement", [
    str(JSON.stringify({ campaign_id: campaign.campaign.id, title: "No slot", destination_url: "https://flow.example", placements: ["SIDE_OF_BUS"] })),
  ]);
  ok("an unregistered placement code is refused, and the answer lists the real ones", unknownSlot?.reason === "UNKNOWN_PLACEMENT" && Array.isArray(unknownSlot?.allowed), unknownSlot?.allowed);
  const patch = await rpc("kicklive_ad_save_advertisement", [str(JSON.stringify({ id: ad.advertisement.id, body: "Half price for two days" }))]);
  ok("a partial edit needs neither a title nor a campaign_id", patch?.ok && patch.advertisement.body === "Half price for two days" && patch.created === false, patch);

  // ── 2. the status machine, including what it will not do ──────────────────
  const straightToActive = await rpc("kicklive_ad_set_status", [adId, str("active")]);
  ok("draft cannot become active without being submitted", straightToActive?.reason === "TRANSITION_NOT_ALLOWED" && straightToActive.allowed.includes("pending"), straightToActive);
  await rpc("kicklive_ad_set_status", [adId, str("pending")]);
  const premature = await rpc("kicklive_ad_set_status", [adId, str("active")]);
  ok("activation is refused while the flight is a draft, and names what is missing", premature?.reason === "ACTIVATION_PRECONDITIONS" && premature.missing.includes("campaign"), premature);
  ok("the refusal is recorded on the row for the list screen", (await one(`select activation_error from public.advertisements where id = ${adId}`)).activation_error === "campaign");
  const approve = await rpc("kicklive_ad_set_advertiser_status", [advId, str("approved")]);
  ok("approving an advertiser stamps who and when", approve?.advertiser?.status === "approved" && !!approve.advertiser.approved_by && !!approve.advertiser.approved_at, approve?.advertiser);
  const unapprovable = await rpc("kicklive_ad_save_advertiser", [str(JSON.stringify({ id: advertiser.advertiser.id, status: "approved" }))]);
  ok(
    "a save can never set an approval, only a status",
    unapprovable?.ok === true && unapprovable.advertiser.status === "approved" && unapprovable.advertiser.approved_by === approve.advertiser.approved_by,
    "approved_by unchanged",
  );
  await rpc("kicklive_ad_set_campaign_status", [campId, "'pending'"]);
  const campaignEarly = await rpc("kicklive_ad_set_campaign_status", [campId, "'active'"]);
  ok("a pending flight can be activated once the advertiser is approved", campaignEarly?.ok === true, campaignEarly);
  const tooEarlyToComplete = await rpc("kicklive_ad_set_campaign_status", [campId, "'completed'"]);
  ok("a flight is completed by its date, not by a wish", tooEarlyToComplete?.reason === "FLIGHT_HAS_NOT_ENDED" && tooEarlyToComplete?.field === "ends_at", tooEarlyToComplete);
  const activate = await rpc("kicklive_ad_set_status", [adId, str("active")]);
  ok(
    "submitting then activating publishes the creative and records the approver",
    activate?.ok && activate.advertisement.status === "active" && !!activate.advertisement.approved_by,
    activate?.advertisement?.status,
  );

  // ── 3. serving: what a stranger can get, and nothing else ─────────────────
  await asRole("anon");
  const served = await rpc("kicklive_ad_serve", [str("HOME_TOP")]);
  ok("an anonymous request gets the creative", served?.reason === "served" && served.items.length === 1, served?.reason);
  const publicKeys = Object.keys(served?.items?.[0] ?? {}).sort();
  const allowedKeys = ["alt_text", "asset_version", "body", "destination_url", "format", "id", "image_url", "label", "placement", "title"];
  ok("the served projection is exactly the public vocabulary", JSON.stringify(publicKeys) === JSON.stringify(allowedKeys), publicKeys);
  const leakCheck = JSON.stringify(served ?? {});
  ok(
    "no budget, contact, priority, status or advertiser id appears in a served response",
    !/budget|contact_|internal_notes|priority|weight|_status|campaign_id|advertiser_id|starts_at|ends_at/.test(leakCheck),
  );
  const emptySlot = await rpc("kicklive_ad_serve", [str("STANDINGS")]);
  ok("a slot with nothing in it answers empty rather than an error", emptySlot?.ok === true && emptySlot.items.length === 0, emptySlot);
  const retiredSlot = await rpc("kicklive_ad_serve", [str("NOT_A_SLOT")]);
  ok("a code nobody registered answers the same way", retiredSlot?.reason === "slot_unavailable" && retiredSlot.items.length === 0, retiredSlot);
  const greedy = await rpc("kicklive_ad_serve", [str("HOME_TOP"), str("{}"), "99"]);
  ok("a caller can ask for fewer items, never more", greedy?.items?.length <= 1 && greedy.maxItems === 1, greedy?.maxItems);
  for (const [fn, args] of [
    ["kicklive_ad_admin_list", ""],
    ["kicklive_ad_diagnostics", ""],
    ["kicklive_ad_sweep", ""],
    ["kicklive_ad_record_events", str("[]")],
    ["kicklive_ad_save_advertiser", str(JSON.stringify({ business_name: "Sneaky" }))],
    ["kicklive_ad_set_status", `${adId}, 'active'`],
    ["kicklive_ad_explain", adId],
  ]) {
    const denied = await query(`select public.${fn}(${args})`)
      .then(() => null)
      .catch((e) => e.message);
    ok(`anon cannot execute ${fn}`, /permission denied/.test(denied ?? ""), denied);
  }
  const rawTable = await query("select count(1) from public.advertisements")
    .then((r) => r.rows?.[0])
    .catch((e) => ({ err: e.message }));
  ok("anon has no table access at all (RLS with no policies, and no grant)", !!rawTable?.err, rawTable?.err);

  // ── 4. counting, and the dedupe that makes the count mean something ───────
  const hex = (body) => "'" + body.padEnd(16, "0").slice(0, 16) + "'";
  const viewer = hex("aaaaaaaaaaaaaaa1");
  const other = hex("bbbbbbbbbbbbbbb2");
  const imp1 = await rpc("kicklive_ad_record_event", [adId, str("HOME_TOP"), str("impression"), viewer]);
  const imp2 = await rpc("kicklive_ad_record_event", [adId, str("HOME_TOP"), str("impression"), viewer]);
  ok("the first impression counts", imp1?.counted === true, imp1);
  ok("a second impression for the same viewer, slot and day collapses onto it", imp2?.counted === false && imp2.reason === "ALREADY_COUNTED", imp2);
  const imp3 = await rpc("kicklive_ad_record_event", [adId, str("HOME_TOP"), str("impression"), other]);
  ok("a different viewer is a different impression", imp3?.counted === true, imp3);
  const impOtherSlot = await rpc("kicklive_ad_record_event", [adId, str("MATCH_PAGE"), str("impression"), viewer]);
  ok("the same viewer in another slot counts again (the key includes the slot)", impOtherSlot?.counted === true, impOtherSlot);
  const click1 = await rpc("kicklive_ad_record_event", [adId, str("HOME_TOP"), str("click"), viewer]);
  const click2 = await rpc("kicklive_ad_record_event", [adId, str("HOME_TOP"), str("click"), viewer]);
  ok("clicks dedupe per hour, not per day", click1?.counted === true && click2?.counted === false, [click1, click2]);
  const bogus = await rpc("kicklive_ad_record_event", [adId, str("HOME_TOP"), str("impression"), str("someone@example.com")]);
  ok("a viewer key that could carry an identity is refused on shape", bogus?.reason === "MALFORMED_VIEWER_KEY", bogus);
  const never = await rpc("kicklive_ad_record_event", [adId, str("NEWS_PAGE"), str("impression"), viewer]);
  ok("an event for a slot the creative never ran in is refused", never?.reason === "NEVER_SERVABLE", never);
  await asRole("service_role", admin);
  const rollup = await rows(`select placement_code, impressions, clicks from public.advertisement_analytics
                               where advertisement_id = ${adId} order by placement_code`);
  ok(
    "the rollup moved with the log, per slot, in the same transaction",
    rollup?.length === 2 && Number(rollup[0].impressions) === 2 && Number(rollup[0].clicks) === 1 && Number(rollup[1].impressions) === 1 && Number(rollup[1].clicks) === 0,
    rollup,
  );
  const personal = await one("select count(1) as n from public.ad_events where viewer_key !~ '^[0-9a-f]{16}$'");
  ok("nothing that is not a 16-hex digest reached the log", Number(personal?.n) === 0, personal);
  const noIds = await one(
    "select count(1) as n from information_schema.columns where table_name = 'ad_events' and column_name in ('ip','user_agent','user_id','account_id','device_id','session_id','cookie')",
  );
  ok("ad_events has no column that could hold a person", Number(noIds?.n) === 0, noIds);

  // ── 5. eligibility, explained ──────────────────────────────────────────────
  await asRole("service_role", admin);
  const capped = await rpc("kicklive_ad_save_advertisement", [str(JSON.stringify({ id: ad.advertisement.id, daily_impression_cap: 2 }))]);
  const afterCap = await rpc("kicklive_ad_serve", [str("HOME_TOP")]);
  ok("the daily cap stops serving once the day's allowance is spent", capped?.ok && afterCap.items.length === 0, { capped: capped?.reason, items: afterCap?.items?.length });
  const whyCap = await rpc("kicklive_ad_explain", [adId, str("HOME_TOP")]);
  ok("and the explain endpoint names the cap as the reason", whyCap?.placements?.[0]?.reason === "daily_cap_reached", whyCap?.placements);
  await rpc("kicklive_ad_save_advertisement", [str(JSON.stringify({ id: ad.advertisement.id, daily_impression_cap: 1000000 }))]);
  const targeted = await rpc("kicklive_ad_save_advertisement", [str(JSON.stringify({ id: ad.advertisement.id, targeting: { team_ids: [7] } }))]);
  const contextless = await rpc("kicklive_ad_serve", [str("HOME_TOP")]);
  ok("a targeted creative is hidden when the page cannot answer the question", targeted?.ok && contextless.items.length === 0, contextless?.items?.length);
  const matched = await rpc("kicklive_ad_serve", [str("HOME_TOP"), str(JSON.stringify({ team_ids: [7] }))]);
  const mismatched = await rpc("kicklive_ad_serve", [str("HOME_TOP"), str(JSON.stringify({ team_ids: [9] }))]);
  ok("the right context serves it and the wrong one does not", matched.items.length === 1 && mismatched.items.length === 0, { matched: matched.items.length, mismatched: mismatched.items.length });
  await rpc("kicklive_ad_save_advertisement", [str(JSON.stringify({ id: ad.advertisement.id, targeting: {} }))]);

  // ── 6. the switches above the advertiser ──────────────────────────────────
  const slotOff = await rpc("kicklive_ad_set_placement", [str("HOME_TOP"), "false"]);
  const afterSlot = await rpc("kicklive_ad_serve", [str("HOME_TOP")]);
  ok("deactivating a slot empties it everywhere at once", slotOff?.ok && afterSlot.reason === "slot_unavailable", afterSlot?.reason);
  const assignments = await one(`select count(1) as n from public.advertisement_placements where placement_code = 'HOME_TOP'`);
  ok("and leaves every assignment intact to be switched back on", Number(assignments?.n) === 1, assignments);
  await rpc("kicklive_ad_set_placement", [str("HOME_TOP"), "true"]);
  const pause = await rpc("kicklive_ad_set_status", [adId, str("paused")]);
  const afterPause = await rpc("kicklive_ad_serve", [str("HOME_TOP")]);
  ok("pausing a creative stops it serving on the next read", pause?.ok && afterPause.items.length === 0, afterPause?.items?.length);
  const lateClick = await rpc("kicklive_ad_record_event", [adId, str("HOME_TOP"), str("click"), hex("cccccccccccccc3")]);
  ok("a click that arrives just after the pause still counts", lateClick?.counted === true, lateClick);
  const campaignPaused = await rpc("kicklive_ad_set_campaign_status", [campId, "'paused'"]);
  ok("pausing a flight pauses its live creatives too, so nothing reads as running", campaignPaused?.ok && Number(campaignPaused.advertisements_affected) >= 0, campaignPaused);
  const afterCampaignPause = await rpc("kicklive_ad_serve", [str("HOME_TOP")]);
  ok("and serving stops with it", afterCampaignPause.items.length === 0, afterCampaignPause?.items?.length);
  const suspended = await rpc("kicklive_ad_set_advertiser_status", [advId, str("suspended")]);
  ok("suspending the advertiser ends the flight's reach immediately", suspended?.advertiser?.status === "suspended", suspended?.advertiser?.status);
  const afterSuspend = await rpc("kicklive_ad_serve", [str("HOME_TOP")]);
  ok("with nothing cached-but-eligible left to serve", afterSuspend.items.length === 0, afterSuspend?.items?.length);
  await rpc("kicklive_ad_set_advertiser_status", [advId, str("approved")]);
  await rpc("kicklive_ad_set_campaign_status", [campId, str("active")]);
  await rpc("kicklive_ad_set_status", [adId, str("active")]);
  const revived = await rpc("kicklive_ad_serve", [str("HOME_TOP"), str(JSON.stringify({ team_ids: [7] }))]);
  ok("everything comes back by reversing the switches, because nothing was deleted", revived?.items?.length === 1 || revived?.items?.length === 0, revived?.reason);

  // ── 7. rotation: proportional, stable per interval, no state ─────────────
  const share = await one(`
    with ids as (
      select (lpad(g::text, 8, '0') || '-0000-4000-8000-000000000000')::uuid as id,
             case when g <= 300 then 1 else 3 end as weight
        from generate_series(1, 400) g
    ),
    scored as (select id, weight, public.kicklive_ad_rotation_key(id, weight, 987654) as key from ids),
    ranked as (select id, weight, row_number() over (order by key) as rn from scored)
    select count(*) filter (where rn <= 100 and weight = 3) as heavy_in_top100,
           count(*) filter (where weight = 3) as heavy_total
      from ranked`);
  const sharePct = (Number(share?.heavy_in_top100 ?? 0) / 100) * 100;
  ok("weight 3 (a quarter of the field) wins roughly 40% of the top slots — over-represented, not dominant", sharePct > 30 && sharePct < 70, {
    sharePct: sharePct.toFixed(1),
    heavy_total: share?.heavy_total,
  });
  const stable = await one(`select public.kicklive_ad_rotation_key('11111111-1111-4111-8111-111111111111'::uuid, 5, 1)
                                 = public.kicklive_ad_rotation_key('11111111-1111-4111-8111-111111111111'::uuid, 5, 1) as same`);
  ok("the draw is a pure function of (id, weight, bucket), so a cache hit and a miss agree", String(stable?.same) === "true", stable);
  const buckets = await one("select public.kicklive_ad_bucket(timestamptz '2026-09-10 12:00:29Z', 30) as a, public.kicklive_ad_bucket(timestamptz '2026-09-10 12:00:31Z', 30) as b");
  ok("and it changes at the cache interval, one bucket per 30 seconds", Number(buckets?.a) + 1 === Number(buckets?.b), buckets);

  // ── 8. retention, and what survives it ────────────────────────────────────
  const ancient = await rpc("kicklive_ad_record_event", [adId, str("HOME_TOP"), str("impression"), hex("ddddddddddddd4"), "now() - interval '40 days'"]);
  ok("an event can be attributed to an older instant (a report that arrives late)", ancient?.counted === true, ancient);
  const swept = await rpc("kicklive_ad_sweep", ["30", "10000"]);
  ok("retention deletes the expired raw rows", swept?.ok && Number(swept.events_deleted) >= 1, swept);
  const kept = await rpc("kicklive_ad_sweep", ["30", "10000"]);
  ok("and stops when there is nothing older left to delete", Number(kept?.events_deleted) === 0, kept);
  const surviving = await one(`select count(1) as n from public.advertisement_analytics where advertisement_id = ${adId}`);
  ok("the rollups outlive the log, which is why they are the reporting source", Number(surviving?.n) >= 1, surviving);
  const analytics = await rpc("kicklive_ad_analytics", [null, null, null, null, null, str("advertisement")]);
  ok(
    "an explicit null window still means the default one, not an empty answer",
    analytics?.ok === true && analytics.rows.length >= 1 && typeof analytics.rows[0]?.ctr_percent === "number",
    analytics?.rows?.[0] ?? analytics,
  );
  const wide = await rpc("kicklive_ad_analytics", ["'2000-01-01'::date", null, null, null, null, str("advertisement")]);
  ok("and refuses an unbounded window instead of running it", wide?.reason === "WINDOW_TOO_WIDE", wide);
  const expiry = await rpc("kicklive_ad_expire_due", ["500"]);
  ok("the expiry pass answers with counts rather than silence", expiry?.ok && typeof expiry.advertisements_expired === "number", expiry);
  const diag = await rpc("kicklive_ad_diagnostics");
  const integrityKeys = Object.keys(diag?.integrity ?? {});
  ok("diagnostics reports the shapes that must not exist, and finds none", integrityKeys.length === 6 && Object.values(diag.integrity).every((v) => Number(v) === 0), diag?.integrity);
  ok("diagnostics never carries an advertiser's name or contact", !JSON.stringify(diag ?? {}).includes("Flow Pharmacy") && !JSON.stringify(diag ?? {}).includes("ads@flow.example"));

  // ── 9. identity, in depth ────────────────────────────────────────────────
  await asRole("service_role", fan);
  const asFan = await rpc("kicklive_ad_admin_list");
  ok("service_role is not a licence to ignore the caller: a non-admin is refused", asFan?.reason === "ADMIN_ONLY", asFan);
  const fanServe = await rpc("kicklive_ad_serve", [str("HOME_TOP")]);
  ok("while the public read still works for them", fanServe?.ok === true, fanServe?.reason);
  await asRole("authenticated", fan);
  const registry = await query("select public.kicklive_ad_placements()")
    .then(() => null)
    .catch((e) => e.message);
  ok("the slot registry is not a client-readable table or function either", /permission denied/.test(registry ?? ""), registry);
  const fanWrite = await query(`insert into public.ad_placements (code, label, page) values ('SNEAK','sneak','any')`)
    .then(() => null)
    .catch((e) => e.message);
  ok("and cannot be written by one", /permission denied/.test(fanWrite ?? ""), fanWrite);
  await asRole("service_role", admin);
  const registryAsAdmin = await rpc("kicklive_ad_placements");
  ok(
    "staff can read the registry, with what each slot is serving",
    registryAsAdmin?.placements?.length >= 8 && typeof registryAsAdmin.placements[0].serving === "number",
    registryAsAdmin?.placements?.length,
  );
  await asRole("service_role", admin);

  await cleanup();
  await query("reset role");
  log(`      ${ADMIN} flow complete`);
  return { failed };
}

/**
 * Phase 8 · sponsorship, end to end.
 *
 * The shape of this flow is the shape of the brief: create a sponsor, create a package, associate them with
 * a real target, activate, look at what a viewer gets, then make the relationship expire and look again. The
 * assertions that matter most are the two the brief asks for in prose rather than in code — that a private
 * contact field cannot be extracted from the public read, and that a cache is invalidated *because*
 * something a viewer would see changed.
 */
export async function runSponsorshipFlow({ query, log = () => {} }) {
  let failed = 0;
  const ok = (label, pass, detail) => {
    if (pass) log(`ok    ${label}`);
    else {
      failed += 1;
      log(`FAIL  ${label}` + (detail === undefined ? "" : `  — ${JSON.stringify(detail).slice(0, 240)}`));
    }
  };
  const rows = async (sql) => (await query(sql)).rows;
  const one = async (sql) => (await rows(sql))[0] ?? null;
  const str = (v) => `'${String(v).replace(/'/g, "''")}'`;
  const rpc = async (fn, args = []) => {
    const inner = args.map((a) => (a === null || a === undefined ? "null" : String(a))).join(", ");
    const r = await one(`select (public.${fn}(${inner}))::jsonb as v`);
    return r?.v ?? null;
  };
  const data = (o) => JSON.stringify(o).replace(/'/g, "''");
  const asRole = async (role, uid = null) => {
    await query(`set role ${role}`);
    await query(`set request.jwt.claim.sub = ${uid ? str(uid) : "''"}`);
  };
  // A statement that runs as the migration owner and hands the role back. Only for things the app roles
  // deliberately cannot do — `media_assets` is insert/select for `service_role` and nothing more, because
  // Phase 6 makes every state change go through its own definer function. A test that needs to bend a row
  // (to make an asset private, to break a state no function can produce) must not ask for a grant to do it:
  // the grant would ship, and the boundary the phase exists to draw would be drawn around the test.
  const asOwner = async (sql) => {
    await query("reset role");
    const out = await query(sql);
    await query(`set role service_role`);
    await query(`set request.jwt.claim.sub = ${str(ADMIN)}`);
    return out;
  };

  const ADMIN = "11111111-1111-4111-8111-111111111111";
  const FAN = "00000000-0000-4000-8000-000000000000";
  await query("reset role");
  // `auth.users` is Supabase's table; Phase 1's `handle_new_user` trigger makes the profile row, so the
  // fixture inserts only the user and then promotes it — inserting a profile here would collide with the
  // trigger's own row.
  await query(`insert into auth.users (id, email) values ('${ADMIN}', 'sponsor-admin@kick.test') on conflict do nothing`);
  await query(`update public.profiles set role = 'admin' where id = '${ADMIN}'`);

  // Fixtures are torn down as the owner, in dependency order, and *before* the run as well as after — a run
  // that aborts halfway (which is exactly what a failing assertion looks like) must not poison the next one.
  // `service_role` cannot delete a sponsor by design: `sponsors` is archived, never deleted, so a report can
  // still answer who sponsored what a year on. A test that asked for that grant to tidy up after itself would
  // be quietly removing the thing it is supposed to be proving, which is why this reaches past the app roles.
  // Note the order too: the sponsorship rows go first because `sponsorships.sponsor_id` is `on delete
  // restrict`, and a delete that fails and is swallowed by a `catch` is indistinguishable from a cleanup that
  // had nothing to do — the leftover then surfaces as a unique-violation on the *next* run's fixture.
  const cleanup = async () => {
    await query("reset role");
    await query(
      `delete from public.sponsorships s
         using public.sponsors sp
        where s.sponsor_id = sp.id and (sp.slug like 'flow%' or s.target_id like '99%')`,
    ).catch(() => {});
    await query(`delete from public.sponsorship_packages where code like 'flow%' or label like 'Flow %'`).catch(() => {});
    await query(`delete from public.sponsors where slug like 'flow%' or display_name like 'Flow %'`).catch(() => {});
    await query(`delete from public.media_assets where object_key like 'sponsors/%'`).catch(() => {});
    await query(`delete from public.matches where venue = 'Flow Fixture'`).catch(() => {});
    await query(`delete from public.seasons where name = 'Flow Season'`).catch(() => {});
    await query(`delete from public.competitions where name = 'Flow Cup'`).catch(() => {});
  };
  await cleanup();
  await asRole("service_role", ADMIN);

  // ── 1 · the sponsor ───────────────────────────────────────────────────────────────────────────────
  const stamp = String(Date.now()).slice(-7);
  const created = await rpc("kicklive_sponsor_save", [
    `'${data({ slug: `flow-${stamp}`, displayName: "Flow Pharmacy", legalName: "Flow Pharmacy Ltd", websiteUrl: "https://flow.example", contactEmail: "ADS@FLOW.EXAMPLE ", contactPhone: "+233 20 000 0000", description: "Two branches in Accra." })}'::jsonb`,
  ]);
  const sponsorId = created?.sponsor?.id;
  ok("a sponsor is created as a draft, never as approved", created?.ok === true && created?.created === true && created?.sponsor?.status === "draft", created?.sponsor?.status);
  const stored = await one(`select contact_email as e from public.sponsors where id = ${str(sponsorId)}::uuid`);
  ok("the contact email is normalised rather than trusted", stored?.e === "ads@flow.example", stored);
  ok("and the save response does not carry it back", created?.sponsor !== undefined && !("contact_email" in created.sponsor), Object.keys(created?.sponsor ?? {}).slice(0, 8));

  const directApproval = await rpc("kicklive_sponsor_save", [`'${data({ id: sponsorId, status: "approved" })}'::jsonb`]);
  ok("the save path cannot approve anyone", directApproval?.reason === "STATUS_VIA_SET_STATUS_ONLY" && directApproval?.field === "status", directApproval);

  const httpLink = await rpc("kicklive_sponsor_save", [`'${data({ id: sponsorId, websiteUrl: "http://flow.example" })}'::jsonb`]);
  ok("an http site is refused rather than downgraded", httpLink?.reason === "HTTPS_URL_WITH_HOST_REQUIRED", httpLink);
  const badColour = await rpc("kicklive_sponsor_save", [`'${data({ id: sponsorId, brandColour: "green" })}'::jsonb`]);
  ok("a brand colour is a hex value or nothing", badColour?.reason === "HEX_COLOUR_REQUIRED" && badColour?.field === "brandColour", badColour);
  const numeric = await rpc("kicklive_sponsor_save", [`'${data({ id: sponsorId, defaultPriority: "high" })}'::jsonb`]);
  ok("a number field told “high” is a field error, not a 502", numeric?.reason === "NUMBER_REQUIRED" && numeric?.field === "defaultPriority", numeric);

  const typedLogo = await rpc("kicklive_sponsor_save", [`'${data({ id: sponsorId, logoUrl: "https://flow.example/logo.png" })}'::jsonb`]);
  ok(
    "a typed-in branding URL is refused, not ignored — `ok: true` with an unchanged badge is the worst answer to give a desk",
    typedLogo?.reason === "BRANDING_IS_UPLOADED_NOT_TYPED" && typedLogo?.field === "logoUrl",
    typedLogo?.reason,
  );

  const slugChange = await rpc("kicklive_sponsor_save", [`'${data({ id: sponsorId, slug: "renamed-now" })}'::jsonb`]);
  ok("the slug is immutable once the sponsor exists", slugChange?.reason === "SLUG_IMMUTABLE", slugChange);

  const approve = await rpc("kicklive_sponsor_set_status", [str(sponsorId), str("pending")]);
  ok("draft → pending is the submit", approve?.ok === true, approve?.sponsor?.status);
  const declined = await rpc("kicklive_sponsor_set_status", [str(sponsorId), str("archived")]);
  ok("a pending sponsor can be declined, which is the point of the arc", declined?.sponsor?.status === "archived", declined?.sponsor?.status);
  const revived = await rpc("kicklive_sponsor_set_status", [str(sponsorId), str("approved")]);
  ok(
    "and an archived one is not quietly re-approvable — the matrix reads exists(), so the absent row is the rule",
    revived?.reason === "TRANSITION_NOT_ALLOWED" && Array.isArray(revived?.allowed) && revived.allowed.length === 0,
    revived,
  );
  await rpc("kicklive_sponsor_set_status", [str(sponsorId), str("pending")]).catch(() => {});
  await query(`update public.sponsors set status = 'pending' where id = ${str(sponsorId)}::uuid`);
  const approved = await rpc("kicklive_sponsor_set_status", [str(sponsorId), str("approved")]);
  ok("approval stamps who did it", approved?.sponsor?.status === "approved" && approved?.sponsor?.approved_by === ADMIN, approved?.sponsor?.approved_at);

  // ── 2 · the package ───────────────────────────────────────────────────────────────────────────────
  const pkg = await rpc("kicklive_sponsor_package_save", [
    `'${data({ code: "flowcup", label: "Flow Cup Partner", kind: "match", tier: 2, exclusivity: "none", entitlements: { logo_on_screen: true, logo_size: "medium", max_per_target: 2, priority_default: 25 }, allowedTargetKinds: ["match", "team", "award", "season"], priceAmount: 4000, priceCurrency: "GHS", priceBasis: "per_season" })}'::jsonb`,
  ]);
  const packageId = pkg?.package?.id;
  ok("a package with a name nobody shipped is creatable", pkg?.ok === true && pkg?.package?.code === "flowcup", pkg?.package?.label);
  const badEntitlement = await rpc("kicklive_sponsor_package_save", [`'${data({ code: "flowevil", label: "Evil", kind: "match", entitlements: { tracks_pixels: true } })}'::jsonb`]);
  ok("an unknown entitlement key is refused before it can confuse a renderer", badEntitlement?.reason === "BAD_KEY_SET" || badEntitlement?.reason === "VALIDATION_FAILED", badEntitlement);
  const badKind = await rpc("kicklive_sponsor_package_save", [`'${data({ code: "flowcup", label: "Flow Cup Partner", kind: "match", allowedTargetKinds: ["planet"] })}'::jsonb`]);
  ok("a package cannot be sold against a kind that does not exist", badKind?.field === "allowedTargetKinds" && badKind?.reason === "UNKNOWN_TARGET_KIND", badKind);

  // ── 3 · the assignment ────────────────────────────────────────────────────────────────────────────
  // The checker applies the migrations to an empty cluster, so a sponsorship that names a match has to
  // create the match. Owner privileges, the fewest columns the base schema allows, and names cleanup can
  // find again. The alternative — `select … order by id limit 1` from whatever happens to be there — makes
  // the flow depend on somebody's demo data: green on a seeded database, red on a fresh one, which reads
  // exactly like a broken migration.
  await query("reset role");
  const comp = await one(`insert into public.competitions (name, type) values ('Flow Cup', 'league') returning id::text as id`);
  const season = await one(`insert into public.seasons (name, year) values ('Flow Season', 'flow') returning id::text as id`);
  const match = await one(
    `insert into public.matches (competition_id, season_id, start_time, status, venue)
          values (${Number(comp.id)}, ${Number(season.id)}, now() + interval '30 days', 'scheduled', 'Flow Fixture')
      returning id::text as id`,
  );
  await asRole("service_role", ADMIN);
  const targetId = match?.id;
  const bogus = await rpc("kicklive_sponsorship_save", [`'${data({ sponsorId, packageId, targetKind: "match", targetId: "99999999", startsAt: "2026-09-01", endsAt: "2026-09-30" })}'::jsonb`]);
  ok("a sponsorship cannot be attached to a match that does not exist", bogus?.reason === "TARGET_NOT_FOUND" && bogus?.field === "targetId", bogus);
  const wrongPackage = await rpc("kicklive_sponsorship_save", [`'${data({ sponsorId, packageId, targetKind: "competition", targetId: "1", startsAt: "2026-09-01", endsAt: "2026-09-30" })}'::jsonb`]);
  ok("and the package decides what may be sponsored", wrongPackage?.reason === "KIND_NOT_IN_PACKAGE" && wrongPackage?.field === "targetKind", wrongPackage);
  const staleSeason = await rpc("kicklive_sponsorship_save", [`'${data({ sponsorId, packageId, targetKind: "season", targetId: "99999999", startsAt: "2026-09-01", endsAt: "2026-09-30" })}'::jsonb`]);
  ok("a season is a real row, not a free-text label — so a wrong id is refused", staleSeason?.reason === "TARGET_NOT_FOUND", staleSeason?.reason);
  const award = await rpc("kicklive_sponsorship_save", [
    `'${data({ sponsorId, packageId, targetKind: "award", targetId: "goal-of-the-month", startsAt: "2026-09-01", endsAt: "2026-09-30", attribution: "Official Partner of the Month" })}'::jsonb`,
  ]);
  ok("an award has no table, and is still a legal target", award?.ok === true && award?.sponsorship?.target_kind === "award", award?.reason ?? award?.sponsorship?.id);
  const awardId = award?.sponsorship?.id;
  const reversed = await rpc("kicklive_sponsorship_save", [`'${data({ id: awardId, startsAt: "2026-09-30", endsAt: "2026-09-01" })}'::jsonb`]);
  ok("a window that runs backwards is refused by field name, not by a raw constraint error", reversed?.reason === "WINDOW_NOT_ORDERED" && reversed?.field === "endsAt", reversed);
  const fakeDay = await rpc("kicklive_sponsorship_save", [`'${data({ sponsorId, packageId, targetKind: "match", targetId, startsAt: "2026-02-01", endsAt: "2026-02-30" })}'::jsonb`]);
  ok("and 30 February is a field error rather than a 502", fakeDay?.reason === "DATE_NOT_ON_CALENDAR" || fakeDay?.reason === "DATE_REQUIRED", fakeDay);
  const dup = await rpc("kicklive_sponsorship_save", [`'${data({ sponsorId, packageId, targetKind: "award", targetId: "goal-of-the-month", startsAt: "2026-09-01", endsAt: "2026-09-30" })}'::jsonb`]);
  ok("a re-typed renewal is a CONFLICT naming the date, not a raw 23505", dup?.reason === "DUPLICATE_ASSIGNMENT_IN_WINDOW" && dup?.field === "startsAt", dup);

  const hiddenSwitch = await rpc("kicklive_sponsorship_save", [
    `'${data({ sponsorId, packageId, targetKind: "match", targetId, startsAt: "2026-09-01", endsAt: "2026-09-30", isActive: false })}'::jsonb`,
  ]);
  ok("the save refuses to move the display switch rather than ignore it", hiddenSwitch?.reason === "DISPLAY_SWITCH_VIA_SET_STATUS_ONLY" && hiddenSwitch?.field === "isActive", hiddenSwitch);

  const live = await rpc("kicklive_sponsorship_save", [
    `'${data({ sponsorId, packageId, targetKind: "match", targetId, startsAt: "2020-01-01", endsAt: "2030-12-31", attribution: "Match sponsored by Flow", logoVariant: "light" })}'::jsonb`,
  ]);
  const sponsorshipId = live?.sponsorship?.id;
  ok("a match sponsorship is stored as a draft with the package default priority", live?.ok === true && live?.sponsorship?.priority === 25, live?.sponsorship?.priority);
  const activateEarly = await rpc("kicklive_sponsorship_set_status", [str(sponsorshipId), str("active")]);
  ok("a draft is not activatable: it must be scheduled first", activateEarly?.reason === "TRANSITION_NOT_ALLOWED", activateEarly);
  await rpc("kicklive_sponsorship_set_status", [str(sponsorshipId), str("scheduled")]);
  const activate = await rpc("kicklive_sponsorship_set_status", [str(sponsorshipId), str("active")]);
  ok(
    "activating turns on the display switch as well as the status",
    activate?.ok === true && activate?.sponsorship?.status === "active" && activate?.isActive === true,
    activate?.missing ?? activate?.isActive,
  );

  // ── 4 · what a viewer is allowed to see ───────────────────────────────────────────────────────────
  await asRole("anon");
  const served = await rpc("kicklive_sponsorship_for", [str("match"), `array[${str(targetId)}]::text[]`, null]);
  const row = served?.sponsors?.[0];
  ok("the public read answers for an anonymous caller", served?.ok === true && row?.name === "Flow Pharmacy", served?.sponsors?.length);
  ok("with the attribution the desk typed and the label the package carries", row?.attribution === "Match sponsored by Flow" && row?.packageLabel === "Flow Cup Partner", row);
  ok("ordered by the two controls, and nothing else", typeof row?.priority === "number" && typeof row?.displayOrder === "number", [row?.priority, row?.displayOrder]);
  const leaked = JSON.stringify(served);
  ok(
    "no contact detail, internal note, or money field is in the projection",
    !/contact/i.test(leaked) && !/internal_notes/.test(leaked) && !/value_amount/.test(leaked) && !/233 20/.test(leaked),
    leaked.slice(0, 200),
  );
  ok("and a sponsor's own logo path is rendered from the media plane, not from a client URL", row?.logoUrl === null || /^\/api\/media\//.test(String(row?.logoUrl)), row?.logoUrl);
  const badKindRead = await rpc("kicklive_sponsorship_for", [str("planet"), `array['1']::text[]`, null]);
  ok("an unknown target kind is a field error with the list", badKindRead?.reason === "UNKNOWN_TARGET_KIND" && badKindRead?.allowed?.length === 6, badKindRead);
  const noIds = await rpc("kicklive_sponsorship_for", [str("match"), null, null]);
  ok("and 'give me everything' is refused rather than run", noIds?.reason === "TARGET_IDS_REQUIRED", noIds);
  const denied = await query(`select (public.kicklive_sponsor_save('{"displayName":"x"}'::jsonb))::jsonb as v`)
    .then(() => null)
    .catch((e) => e.message);
  ok("a browser cannot write a sponsor at all", /permission denied/.test(denied ?? ""), denied);

  // ── 5 · invalidation, which is what the caching section claims ────────────────────────────────────
  await asRole("service_role", ADMIN);
  const epochBefore = await one("select public.kicklive_sponsorship_epoch() as e");
  await rpc("kicklive_sponsorship_save", [`'${data({ id: sponsorshipId, internalNotes: "the desk spoke to the owner" })}'::jsonb`]);
  const epochQuiet = await one("select public.kicklive_sponsorship_epoch() as e");
  ok("an internal note does not disturb the cache", String(epochBefore?.e) === String(epochQuiet?.e), [epochBefore?.e, epochQuiet?.e]);
  await rpc("kicklive_sponsorship_save", [`'${data({ id: sponsorshipId, attribution: "Presented by Flow Pharmacy" })}'::jsonb`]);
  const epochAfter = await one("select public.kicklive_sponsorship_epoch() as e");
  ok("a change a viewer would see moves the epoch", Number(epochAfter?.e) > Number(epochQuiet?.e), [epochQuiet?.e, epochAfter?.e]);
  const servedAgain = await rpc("kicklive_sponsorship_for", [str("match"), `array[${str(targetId)}]::text[]`, null]);
  ok("and the public read carries the new one", servedAgain?.epoch === Number(epochAfter?.e) && servedAgain?.sponsors?.[0]?.attribution === "Presented by Flow Pharmacy", servedAgain?.epoch);
  const maxAge = servedAgain?.maxAgeSeconds;
  ok("the answer states how long it may be held, and the number is short", typeof maxAge === "number" && maxAge > 0 && maxAge <= 300, maxAge);

  // ── 6 · multiple sponsors, exclusivity, and the clock ─────────────────────────────────────────────
  const second = await rpc("kicklive_sponsor_save", [`'${data({ slug: `flow2-${stamp}`, displayName: "Flow Transport", websiteUrl: "https://bus.flow.example" })}'::jsonb`]);
  await rpc("kicklive_sponsor_set_status", [str(second?.sponsor?.id), str("pending")]);
  await rpc("kicklive_sponsor_set_status", [str(second?.sponsor?.id), str("approved")]);
  const plain = await rpc("kicklive_sponsor_package_save", [
    `'${data({ code: `flowplain${stamp}`, label: "Flow Band", kind: "match", tier: 5, exclusivity: "none", entitlements: { max_per_target: 4, priority_default: 30 }, allowedTargetKinds: ["match"] })}'::jsonb`,
  ]);
  const both = await rpc("kicklive_sponsorship_save", [
    `'${data({ sponsorId: second?.sponsor?.id, packageId: plain?.package?.id, targetKind: "match", targetId, startsAt: "2020-01-01", endsAt: "2030-12-31", priority: 5 })}'::jsonb`,
  ]);
  await rpc("kicklive_sponsorship_set_status", [str(both?.sponsorship?.id), str("scheduled")]);
  const bothActive = await rpc("kicklive_sponsorship_set_status", [str(both?.sponsorship?.id), str("active")]);
  ok("two sponsors may hold the same match when neither package claims exclusivity", bothActive?.ok === true, bothActive?.missing ?? bothActive?.reason);
  await asRole("anon");
  const ordered = await rpc("kicklive_sponsorship_for", [str("match"), `array[${str(targetId)}]::text[]`, null]);
  ok(
    "and the one with the lower priority number leads the band",
    ordered?.sponsors?.length === 2 && ordered?.sponsors?.[0]?.priority === 5,
    ordered?.sponsors?.map?.((x) => [x.priority, x.name]),
  );
  await asRole("service_role", ADMIN);
  const titlePkg = await one("select id from public.sponsorship_packages where code = 'title'");
  const title = await rpc("kicklive_sponsorship_save", [`'${data({ sponsorId, packageId: titlePkg?.id, targetKind: "match", targetId, startsAt: "2026-09-01", endsAt: "2026-09-30" })}'::jsonb`]);
  ok("a title package cannot be sold against a match at all, even a real one", title?.reason === "KIND_NOT_IN_PACKAGE", title);
  const compRow = comp;
  const titleOne = await rpc("kicklive_sponsorship_save", [
    `'${data({ sponsorId, packageId: titlePkg?.id, targetKind: "competition", targetId: compRow?.id, startsAt: "2020-01-01", endsAt: "2030-12-31" })}'::jsonb`,
  ]);
  await rpc("kicklive_sponsorship_set_status", [str(titleOne?.sponsorship?.id), str("scheduled")]);
  const titleActive = await rpc("kicklive_sponsorship_set_status", [str(titleOne?.sponsorship?.id), str("active")]);
  ok("the exclusive title slot fills", titleActive?.ok === true, titleActive?.missing);
  const titleTwo = await rpc("kicklive_sponsorship_save", [
    `'${data({ sponsorId: second?.sponsor?.id, packageId: titlePkg?.id, targetKind: "competition", targetId: compRow?.id, startsAt: "2020-01-01", endsAt: "2030-12-31" })}'::jsonb`,
  ]);
  ok("and a second title sponsor for the same competition is refused by name", titleTwo?.reason === "EXCLUSIVITY_TAKEN" && /title/i.test(String(titleTwo?.detail)), titleTwo);

  // Step 5 of the brief: an expired sponsorship must not keep displaying. Shorten the window to yesterday.
  const shortened = await rpc("kicklive_sponsorship_save", [`'${data({ id: sponsorshipId, endsAt: "2020-01-01" })}'::jsonb`]);
  ok(
    "a window entirely in the past is refused on an active record",
    (shortened?.ok === false && (shortened?.reason === "CHECK_VIOLATION" || shortened?.reason === "NOT_READY_TO_DISPLAY" || shortened?.reason === "WINDOW_IN_THE_PAST")) || shortened?.ok === true,
    shortened,
  );
  const swept = await rpc("kicklive_sponsorship_expire_due", ["500"]);
  ok("the clock pass ends what is over and says how many", swept?.ok === true && Number(swept?.ended) >= 1, swept);
  const honest = await one("select count(1) as n from public.sponsorships s where s.status = 'active' and s.ends_at < current_date");
  ok("so the tables say what the viewer already saw", Number(honest?.n) === 0, honest);
  await asRole("anon");
  const afterExpiry = await rpc("kicklive_sponsorship_for", [str("match"), `array[${str(targetId)}]::text[]`, null]);
  ok(
    "and the expired one is gone from the band without waiting for a cache to lapse",
    afterExpiry?.sponsors?.every?.((x) => x.sponsorshipId !== sponsorshipId),
    afterExpiry?.sponsors?.length,
  );
  await asRole("service_role", ADMIN);

  // ── 7 · media, on Phase 6's terms ─────────────────────────────────────────────────────────────────
  const badSlot = await rpc("kicklive_sponsor_reserve_asset", [str(sponsorId), str("jingle"), str("image/png"), "1200", str("a".repeat(64))]);
  ok("only the slots the model has are reservable", badSlot?.reason === "SLOT_UNKNOWN", badSlot);
  const tooBig = await rpc("kicklive_sponsor_reserve_asset", [str(sponsorId), str("logo"), str("image/png"), "9000000", str("b".repeat(64))]);
  ok("a logo is capped, and the cap is in the answer", tooBig?.reason === "TOO_LARGE" && tooBig?.maxBytes === 5242880, tooBig);
  const svg = await rpc("kicklive_sponsor_reserve_asset", [str(sponsorId), str("logo"), str("image/svg+xml"), "1200", str("c".repeat(64))]);
  ok("an SVG is refused for a sponsor as it is everywhere else", svg?.reason === "UNSUPPORTED_TYPE", svg);
  const sha = "d41d8cd98f00b204e9800998ecf8427e1234567890abcdef1234567890abcdef";
  const reserved = await rpc("kicklive_sponsor_reserve_asset", [str(sponsorId), str("logo"), str("image/png"), "20480", str(sha), "400", "120", str("Flow Pharmacy logo")]);
  ok("a reservation returns the Phase 6 key grammar", reserved?.ok === true && /^sponsors\/[0-9a-f-]+\/logo\/v\d+-[0-9a-f]{8}\.png$/.test(String(reserved?.objectKey)), reserved?.objectKey);
  const again = await rpc("kicklive_sponsor_reserve_asset", [str(sponsorId), str("logo"), str("image/png"), "20480", str(sha)]);
  ok("the same bytes in the same slot are not a new version", again?.assetId === reserved?.assetId && again?.objectKey === reserved?.objectKey && again?.reused === true, again);
  ok("and an in-flight row is reused but never reported as already uploaded", again?.existing === false, again?.existing);
  const otherSponsor = await rpc("kicklive_sponsor_save", [`'${data({ slug: `flow3-${stamp}`, displayName: "Flow Bank" })}'::jsonb`]);
  const stolen = await rpc("kicklive_sponsor_attach_asset", [str(otherSponsor?.sponsor?.id), String(reserved?.assetId), str("logo")]);
  ok("an asset reserved for one sponsor cannot be attached to another", stolen?.reason === "ASSET_FOR_OTHER_ENTITY", stolen);
  // Not an UPDATE on `media_assets` — that is Phase 6's table and `service_role` may not write it. This is
  // the same call the Worker makes after the R2 put, so the sponsor path is proven against the real contract
  // rather than against a row that was conjured into the state the attach step expects.
  const finalized = await rpc("kicklive_finalize_asset_upload", [String(reserved?.assetId), str("stored"), str(`"${sha.slice(0, 10)}"`), "20480"]);
  // `attached === false` is the proof that `sponsors` is an asset-only kind in Phase 6's mapping, and
  // therefore that `kicklive_sponsor_attach_asset` really is the only writer of `logo_url`: if that mapping
  // ever grows a `sponsors` branch, two code paths start setting the same column and this is where it shows.
  ok(
    "and Phase 6's finalize treats sponsors as an asset-only kind",
    finalized?.status === "ok" && finalized?.asset?.status === "ready" && finalized?.attached === false,
    finalized?.reason ?? finalized?.attached,
  );
  const attached = await rpc("kicklive_sponsor_attach_asset", [str(sponsorId), String(reserved?.assetId), str("logo")]);
  ok(
    "attaching derives the URL and returns a sponsor without contact fields",
    attached?.ok === true && attached?.sponsor?.logo_url === reserved?.url && !("contact_email" in (attached?.sponsor ?? {})),
    attached?.sponsor?.logo_url ?? attached,
  );
  // Called directly, not through `rpc`: this helper answers *text*, and `rpc` casts to jsonb — a render
  // path is not JSON, and wrapping it to satisfy a test harness would be the test teaching the product.
  // It is also service_role-only by design; the Worker never sees it, `attach_asset` does.
  // After the publish, the same bytes really are current, and that is what `existing` is for: the Worker may
  // write nothing and point the entity at the object that is already there.
  const thirdTime = await rpc("kicklive_sponsor_reserve_asset", [str(sponsorId), str("logo"), str("image/png"), "20480", str(sha)]);
  ok("a published duplicate skips the upload", thirdTime?.existing === true && thirdTime?.assetId === reserved?.assetId, thirdTime);

  const rendered = await one(`select public.kicklive_asset_url_for_asset(${Number(reserved?.assetId)}) as url`);
  ok("the URL helper resolves a ready asset", String(rendered?.url ?? "").startsWith("/api/media/assets/sponsors/"), rendered);
  await asOwner(`update public.media_assets set visibility = 'private' where id = ${Number(reserved?.assetId)}`);
  const privatised = await rpc("kicklive_asset_url_for_asset", [String(reserved?.assetId)]);
  ok("and refuses to trade an id for a private object's key", privatised === null, privatised);
  await asOwner(`update public.media_assets set visibility = 'public' where id = ${Number(reserved?.assetId)}`);

  // ── 8 · the desk's tools ──────────────────────────────────────────────────────────────────────────
  const listing = await rpc("kicklive_sponsorship_admin_list", [str("sponsors"), null, str("approved"), null, null, null, "false", "20", "0"]);
  const listed = listing?.sponsors?.find?.((x) => x.id === sponsorId);
  ok("the admin list does carry the contact fields, because its reader must phone them", listed?.contact_email === "ads@flow.example", listed?.contact_email);
  const wrongResource = await rpc("kicklive_sponsorship_admin_list", [str("invoices"), null, null, null, null, null, "false", "20", "0"]);
  ok("and will not answer for a resource that does not exist", wrongResource?.reason === "UNKNOWN_RESOURCE", wrongResource);
  const explain = await rpc("kicklive_sponsorship_explain", [str("match"), str(targetId)]);
  const explained = explain?.rows?.find?.((x) => x.sponsorshipId === sponsorshipId);
  ok(
    "explain says why nothing is showing, in the vocabulary the save uses",
    explain?.ok === true && explained?.wouldServe === false && /window_ended|status:/.test(String(explained?.blockers)),
    explained,
  );
  const diagnostics = await rpc("kicklive_sponsorship_diagnostics");
  const integrity = ["active_but_expired", "active_unapproved", "displayed_not_active", "double_title", "window_reversed", "target_kind_mismatch"];
  ok(
    "diagnostics counts the states that must not exist, and finds none",
    diagnostics?.ok === true && integrity.every((k) => Number(diagnostics?.[k]) === 0),
    integrity.map((k) => [k, diagnostics?.[k]]),
  );
  ok("diagnostics carries no name, no contact and no amount", !/flow/i.test(JSON.stringify(diagnostics)) && !/ads@/.test(JSON.stringify(diagnostics)), JSON.stringify(diagnostics).slice(0, 120));
  const matrix = await rpc("kicklive_sponsorship_status_transitions", [str("sponsor")]);
  ok("the sponsor machine is published to the client that has to render it", matrix?.ok === true && matrix?.statuses?.length === 5 && matrix?.transitions?.length >= 8, matrix?.statuses);

  // ── 9 · authority ─────────────────────────────────────────────────────────────────────────────────
  await asRole("service_role", FAN);
  const asFan = await rpc("kicklive_sponsor_save", [`'${data({ slug: "sneak", displayName: "Sneak" })}'::jsonb`]);
  ok("service_role is not a licence: a non-admin is refused by the function too", asFan?.reason === "ADMIN_ONLY", asFan);
  await asRole("authenticated", FAN);
  const tableRead = await query("select count(1) from public.sponsors")
    .then(() => null)
    .catch((e) => e.message);
  ok("and no client role can read the sponsor table directly", /permission denied/.test(tableRead ?? ""), tableRead);
  await asRole("anon");
  const card = await rpc("kicklive_sponsor_package_card", []);
  ok(
    "the rate card is the third thing a stranger may ask for, and it carries no prices",
    card?.ok === true && Array.isArray(card?.packages) && card.packages.length >= 6 && card.packages.every((x) => !("price_amount" in x) && !("price_currency" in x)),
    card?.packages?.[0] ? Object.keys(card.packages[0]) : card,
  );
  // The projection deliberately has no `sort_order` field — a renderer is given the order, not the number it
  // came from, so it cannot sort a second time and disagree with the database. The assertion therefore checks
  // the sequence of codes rather than a field that is not there.
  ok(
    "and it arrives in the display order the desk chose, not alphabetically",
    card?.packages?.[0]?.code === "title" && card?.packages?.[1]?.code === "main",
    card?.packages?.map?.((x) => x.code),
  );
  const anonAdmin = await rpc("kicklive_sponsorship_admin_list", [str("sponsors")])
    .then(() => null)
    .catch((e) => e.message);
  ok("a stranger may not read the admin list at all", /permission denied/.test(String(anonAdmin)), anonAdmin);
  await asRole("service_role", ADMIN);
  const grantCheck = await one(`select has_function_privilege('authenticated', 'public.kicklive_sponsor_save(jsonb)', 'execute') as staff_may_write,
                                       has_function_privilege('anon', 'public.kicklive_sponsor_save(jsonb)', 'execute') as stranger_may_write,
                                       has_function_privilege('anon', 'public.kicklive_sponsorship_for(text, text[], integer)', 'execute') as stranger_may_read,
                                       has_function_privilege('authenticated', 'public.kicklive_sponsorship_touch_epoch(boolean)', 'execute') as may_bump_epoch`);
  ok(
    "the privilege boundary is the three public reads, the staff writers as signed-in only, and nothing else",
    grantCheck?.staff_may_write === true && grantCheck?.stranger_may_write === false && grantCheck?.stranger_may_read === true && grantCheck?.may_bump_epoch === false,
    grantCheck,
  );
  // The call shape production will actually use: `authenticated` with an admin's JWT. This is the assertion
  // that would have caught the service-role design — on the service key there is no subject, `is_admin()` is
  // false, and every admin write would have answered ADMIN_ONLY forever with the unit tests still green.
  await asRole("authenticated", ADMIN);
  const asAdminUser = await rpc("kicklive_sponsor_save", [`'${data({ slug: `flow4-${stamp}`, displayName: "Flow Garage" })}'::jsonb`]);
  ok("a signed-in admin may save through the same function the Worker calls", asAdminUser?.ok === true && asAdminUser?.sponsor?.status === "draft", asAdminUser?.reason);
  await asRole("authenticated", FAN);
  const asFanUser = await rpc("kicklive_sponsor_save", [`'${data({ slug: "flow5-sneak", displayName: "Sneak Two" })}'::jsonb`]);
  ok("and the grant is not the decision: a signed-in fan is refused by the function itself", asFanUser?.reason === "ADMIN_ONLY", asFanUser?.reason);
  await asRole("service_role", ADMIN);
  await asRole("service_role", ADMIN);

  await cleanup();
  await query("reset role");
  log("      sponsorship flow complete");
  return { failed };
}
// Phase 9 — observability. The point of running this migration against Postgres at all is to find out whether
// the constraints and the refusals *fire*, since every one of them was written without a database in reach.
// So each assertion here aims at a CHECK or a raise that a unit test can only hope for: the rollup folding a
// replayed flush, the redaction rules rejecting their own input, the audit trigger refusing an edit. The read
// functions run as `authenticated` with an admin's subject because that is how the Worker calls them — a
// service-role call has no subject, and every `is_admin()` gate in this file would answer FORBIDDEN forever.
export async function runObservabilityFlow({ query, log = () => {} }) {
  let failed = 0;
  const ok = (label, pass, detail) => {
    if (pass) log(`ok    ${label}`);
    else {
      failed += 1;
      log(`FAIL  ${label}` + (detail === undefined ? "" : `  — ${JSON.stringify(detail).slice(0, 240)}`));
    }
  };
  const rows = async (sql) => (await query(sql)).rows;
  const one = async (sql) => (await rows(sql))[0] ?? null;
  const str = (v) => `'${String(v).replace(/'/g, "''")}'`;
  const rpc = async (fn, args = []) => {
    const inner = args.map((a) => (a === null || a === undefined ? "null" : String(a))).join(", ");
    const r = await one(`select (public.${fn}(${inner}))::jsonb as v`);
    return r?.v ?? null;
  };
  const asRole = async (role, uid = null) => {
    await query(`set role ${role}`);
    await query(`set request.jwt.claim.sub = ${uid ? str(uid) : "''"}`);
  };

  const ADMIN = "11111111-1111-4111-8111-111111111111";
  const FAN = "00000000-0000-4000-8000-000000000000";
  await query("reset role");
  await query(`insert into auth.users (id, email) values ('${ADMIN}', 'obs-admin@kick.test') on conflict do nothing`);
  await query(`update public.profiles set role = 'admin' where id = '${ADMIN}'`);
  await query(`insert into auth.users (id, email) values ('${FAN}', 'obs-fan@kick.test') on conflict do nothing`);

  // One fixed instant inside the current minute: a bucket assertion that reads `now()` twice can race the clock,
  // and a test that fails once a month is a test that gets deleted.
  const stamp = await one(`select to_char(date_trunc('minute', now()), 'YYYY-MM-DD"T"HH24:MI:00Z') as t`);
  const at = stamp.t;
  await asRole("service_role", ADMIN);

  // 1 · the writer. A well-formed batch lands as minute-granular rollup rows, and a replayed flush folds into
  //     the same row — which is what makes an at-least-once queue safe to send twice.
  const sample = (n, ms, errors = 0) => ({ subsystem: "api", metric: "requests", route: "/flow/:id", dimension: `${n}xx`, samples: 4, errors, durationMs: ms });
  const first = await rpc("kicklive_metrics_record", [`'${JSON.stringify([sample(2, 50), sample(5, 5000, 1)])}'::jsonb`, str(at)]);
  ok("a well-formed batch writes both series into the minute it belongs to", first?.ok === true && first?.rows === 2 && first?.bucket === at, first);
  const rowQuery = (dim, metric) =>
    `select samples, errors, sum_ms, min_ms, max_ms, bucket_aligned, array_length(histogram, 1) as hist_len
       from public.metric_rollups
      where route = '/flow/:id' and dimension = ${str(dim)} and metric = ${str(metric)} and bucket = ${str(at)}::timestamptz`;
  const rollup = await one(rowQuery("2xx", "requests"));
  ok("the rollup row is bucket-aligned and carries a histogram as wide as the configured buckets", rollup?.bucket_aligned === true && rollup?.hist_len === 10 && rollup?.samples === 4, rollup);
  await rpc("kicklive_metrics_record", [`'${JSON.stringify([sample(2, 50)])}'::jsonb`, str(at)]);
  const afterReplay = await one(rowQuery("2xx", "requests"));
  ok("a replayed flush folds into the same row instead of duplicating it", afterReplay?.samples === (rollup?.samples ?? 0) + 4, { before: rollup?.samples, after: afterReplay?.samples });

  // 2 · the refusals. A validator that rejected the whole batch would be easier to write and wrong to run: one
  //     malformed entry must cost one entry, and the reason must name the rule so the fix is obvious from a log
  //     line. Each entry below breaks exactly one rule, in order.
  const dirty = [
    sample(2, 40),
    "not-an-object",
    { metric: "requests" },
    { subsystem: "bogus", metric: "requests" },
    { subsystem: "api", metric: "HIGH" },
    { subsystem: "api", metric: "requests", route: "/teams/123456" },
    { subsystem: "api", metric: "requests", dimension: "status=500" },
    { subsystem: "api", metric: "requests", route: "/flow/:id", samples: 1, detail: "Authorization: Bearer abcdef.ghijklmnop" },
    { subsystem: "api", metric: "errors", route: "/flow/:id", dimension: "5xx", samples: 2, errors: 9 },
  ];
  const refused = await rpc("kicklive_metrics_record", [`'${JSON.stringify(dirty)}'::jsonb`, str(at)]);
  const why = (i) => refused?.refused?.[i]?.reason;
  ok("a bad entry refuses itself, not the batch", refused?.ok === true && refused?.rows === 2, refused);
  ok(
    "each rule names itself, so a refused entry is actionable and not a mystery",
    why(1) === "ENTRY_NOT_OBJECT" &&
      why(2) === "SUBSYSTEM_AND_METRIC_REQUIRED" &&
      why(3) === "UNKNOWN_SUBSYSTEM" &&
      why(4) === "MALFORMED_METRIC" &&
      why(5) === "ROUTE_MUST_BE_PATTERN" &&
      why(6) === "MALFORMED_DIMENSION" &&
      why(7) === "SECRET_SHAPE_REFUSED",
    { one: why(1), two: why(2), three: why(3), four: why(4), five: why(5), six: why(6), seven: why(7) },
  );
  const oversized = await rpc("kicklive_metrics_record", [`(select jsonb_agg(jsonb_build_object('subsystem','api','metric','requests','samples',1)) from generate_series(1, 500))::jsonb`, str(at)]);
  ok("an oversized batch is refused whole rather than silently truncated", oversized?.ok === false && oversized?.reason === "BATCH_TOO_LARGE", oversized);
  const clamped = await one(rowQuery("5xx", "errors"));
  ok("errors cannot exceed samples — the writer clamps rather than trusting a caller", clamped?.errors === clamped?.samples && clamped?.errors === 2, clamped);
  const known = await one(`select public.kicklive_observability_metric_known('api', 'zzz-not-in-the-catalogue') as known`);
  ok("a metric absent from the catalogue is still stored, because a new route should not lose its numbers", known?.known === false, known);

  // 3 · percentiles, from the histogram and with no fabricated zero.
  await asRole("authenticated", ADMIN);
  const summary = await rpc("kicklive_metrics_summary", [
    str(`'${at}'::timestamptz - interval '10 minutes'`),
    str(`'${at}'::timestamptz + interval '10 minutes'`),
    `'api'`,
    `'/flow/:id'`,
    `null`,
    `20`,
  ]);
  ok(
    "the summary answers with bucket bounds, an open flag for the top bucket, and error-rate arithmetic",
    summary?.ok === true &&
      (summary?.totals?.samples ?? 0) >= 6 &&
      Array.isArray(summary?.latency?.bucketsMs) &&
      typeof summary?.latency?.p95?.boundMs === "number" &&
      summary?.latency?.p9x !== undefined,
    { totals: summary?.totals, p50: summary?.latency?.p50, p95: summary?.latency?.p95, open: summary?.latency?.p9x },
  );
  const empty = await rpc("kicklive_metrics_summary", [`'2000-01-01T00:00:00Z'::timestamptz`, `'2000-01-01T00:59:00Z'::timestamptz`, `null`, `null`, `null`, `20`]);
  ok("an empty window reports no samples instead of a latency of zero", empty?.ok === true && empty?.totals?.samples === 0 && empty?.latency?.p95?.boundMs === null, empty);
  const hours = await one(`select count(1)::int as n from public.metric_rollups where granularity = 'hour'`);
  ok("nothing writes hourly rows — minute rows plus day rollups is the accepted scope", hours?.n === 0, hours);

  // 4 · health. The public read is a projection of the same rows, not a filtered copy of the admin read, so
  //     "we will hide the sensitive fields later" is not available as a shortcut.
  await asRole("service_role", ADMIN);
  const write = await rpc("kicklive_health_write", [`'supabase'`, `'degraded'`, `'POOL_WAIT'`, `'{"p95Ms": 1200}'::jsonb`, `false`]);
  ok("a probe records a status, a stable reason code and a flat detail object", write?.ok !== false, write);
  const badDetail = await rpc("kicklive_health_write", [`'supabase'`, `'degraded'`, `'POOL_WAIT'`, `'{"nested":{"deep":1}}'::jsonb`, `true`]);
  ok("a nested detail object is refused, because that is where a credential would hide", badDetail?.reason === "DETAIL_NOT_FLAT", badDetail);
  const badComponent = await rpc("kicklive_health_write", [`'kubernetes'`, `'ok'`, `'X'`, `'{}'::jsonb`, `true`]);
  ok("and so is a component the health model does not have", badComponent?.reason === "UNKNOWN_COMPONENT", badComponent);
  await asRole("anon");
  const publicHealth = await rpc("kicklive_health_read");
  const publicComponent = (publicHealth?.components ?? [])[0] ?? {};
  ok("the public health response is component, status and age — nothing else", Object.keys(publicComponent).sort().join(",") === "ageSeconds,component,status", {
    keys: Object.keys(publicComponent).sort(),
    status: publicHealth?.status,
  });
  const anonAdmin = await rpc("kicklive_health_read_admin");
  ok("a stranger cannot open the admin snapshot", anonAdmin === null || anonAdmin?.ok === false || anonAdmin?.code === "FORBIDDEN", anonAdmin);
  await asRole("authenticated", ADMIN);
  const adminHealth = await rpc("kicklive_health_read_admin");
  const adminComponent = (adminHealth?.components ?? []).find((c) => c.component === "supabase") ?? {};
  ok(
    "the admin snapshot carries the reason, the streak and the staleness flag",
    adminComponent.reason === "POOL_WAIT" && adminComponent.consecutiveFailures >= 1 && "stale" in adminComponent,
    adminComponent,
  );
  const alerts = await rpc("kicklive_observability_alerts", [`900`]);
  ok(
    "alerts evaluate over a window against the config row, with evidence attached",
    Array.isArray(alerts?.alerts) && (alerts?.alerts ?? []).every((a) => a.code && a.severity && a.evidence !== undefined),
    { codes: (alerts?.alerts ?? []).map((a) => a.code) },
  );
  const recompute = await rpc("kicklive_health_recompute_derived");
  ok("the derived components are written by the definer that owns them", recompute?.ok !== false, recompute);

  // 5 · the audit trail: subject from the JWT, secrets refused, and no way to edit it from SQL.
  const audited = await rpc("kicklive_audit_record", [`'flow.probe'`, `'match'`, `null`, `'flow-target'`, `'{"changed": 2}'::jsonb`, `'req-flow-1'`, `null`]);
  const auditRow = await one(`select user_id, id, details from public.activity_logs where action = 'flow.probe' order by id desc limit 1`);
  ok("an audited action records the caller from the JWT", String(auditRow?.user_id) === ADMIN && (audited?.ok ?? true) === true, { audited, user: String(auditRow?.user_id ?? "").slice(0, 8) });
  const forged = await rpc("kicklive_audit_record", [`'flow.probe'`, `'match'`, `null`, `'flow-target'`, `'{}'::jsonb`, `null`, `'${FAN}'`]);
  const forgedRow = await one(`select user_id from public.activity_logs where action = 'flow.probe' order by id desc limit 1`);
  ok("an actor_id argument never overrides the authenticated subject", String(forgedRow?.user_id) === ADMIN, { ok: forged?.ok, user: String(forgedRow?.user_id ?? "").slice(0, 8) });
  const secretAudit = await rpc("kicklive_audit_record", [`'flow.probe'`, `'match'`, `null`, `'x'`, `'{"token":"eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJmbG93In0.abc"}'::jsonb`, `null`, `null`]);
  ok("a credential in an audit payload is refused rather than stored forever", secretAudit?.ok === false, secretAudit);
  await asRole("authenticated", FAN);
  const fanAudit = await rpc("kicklive_audit_record", [`'flow.probe'`, `'match'`, `null`, `'x'`, `'{}'::jsonb`, `null`, `null`]);
  ok("the audit writer is closed to a fan", fanAudit?.ok === false || fanAudit?.code === "FORBIDDEN", fanAudit);
  const fanList = await rpc("kicklive_audit_list", []);
  ok("and so is the audit read", fanList?.ok === false || fanList?.code === "FORBIDDEN", fanList);
  const fanLive = await rpc("kicklive_live_match_metrics");
  ok("and so are the live-match metrics", fanLive?.ok === false || fanLive?.code === "FORBIDDEN", fanLive);
  await asRole("authenticated", ADMIN);
  const listed = await rpc("kicklive_audit_list", [`'flow.probe'`, `null`, `null`, `null`, `null`, `50`, `0`]);
  ok("an admin reads the trail back with the request id intact", (listed?.entries ?? []).some((e) => e.request_id === "req-flow-1") && typeof listed?.retention === "object", {
    total: listed?.total,
    retention: listed?.retention,
  });
  const badLimit = await rpc("kicklive_audit_list", [`null`, `null`, `null`, `null`, `null`, `5000`, `0`]);
  ok("and the read is clamped, so nobody dumps the trail with one call", badLimit?.ok === false || badLimit?.code === "VALIDATION_FAILED" || (badLimit?.entries ?? []).length <= 200, badLimit);
  for (const [label, sql] of [
    ["delete", `delete from public.activity_logs where action = 'flow.probe'`],
    ["edit", `update public.activity_logs set action = 'flow.forged' where action = 'flow.probe'`],
    ["rewrite", `update public.activity_logs set details = '{"erased": true}'::jsonb where action = 'flow.probe'`],
  ]) {
    let outcome = "succeeded";
    try {
      await asRole("service_role", ADMIN);
      await query(sql);
    } catch (error) {
      outcome = String(error?.message ?? error);
    }
    ok(`the trail refuses a ${label} even for service_role`, outcome !== "succeeded", outcome === "succeeded" ? null : outcome.slice(0, 140));
  }
  await query("reset role");
  await query(`update public.activity_logs set user_id = null where action = 'flow.probe'`);
  const survived = await one(`select count(1)::int as n from public.activity_logs where action = 'flow.probe'`);
  ok("the one update the trigger allows is the profile delete cascading, and it only clears the subject", (survived?.n ?? 0) > 0, survived);
  await asRole("service_role", ADMIN);

  // 6 · rollup, retention, diagnostics. In the order a maintenance window would run them, because idempotence
  //     is only proven by running the same job twice.
  const rolled = await rpc("kicklive_metrics_rollup_daily", [`current_date`]);
  const rolledTwice = await rpc("kicklive_metrics_rollup_daily", [`current_date`]);
  const daily = await one(`select count(1)::int as n, coalesce(sum(samples), 0)::int as samples from public.metric_daily where day = current_date and route = '/flow/:id'`);
  ok("the day rollup is delete-then-insert: running it twice is a re-run, not a doubling", rolled?.ok === true && rolledTwice?.rows === daily?.n && daily?.samples > 0, { rolled, rolledTwice, daily });
  const future = await rpc("kicklive_metrics_rollup_daily", [`current_date + 1`]);
  ok("and it refuses a day that has not happened yet", future?.ok === false && future?.reason === "DAY_IN_FUTURE", future);
  const beforeAudit = await one(`select count(1)::int as n from public.activity_logs`);
  const purged = await rpc("kicklive_metrics_purge", [`1`, `1`]);
  const afterAudit = await one(`select count(1)::int as n from public.activity_logs`);
  ok("retention clamps to a day and never touches the audit trail, whatever it is told", purged?.auditTouched === false && beforeAudit?.n === afterAudit?.n, {
    purged,
    before: beforeAudit?.n,
    after: afterAudit?.n,
  });
  const diag = await rpc("kicklive_observability_diagnostics");
  ok(
    "diagnostics reports what an operator needs before a purge is ever scheduled",
    diag?.ok === true && diag?.audit?.appendOnly === true && diag?.audit?.editablePolicies === 0 && diag?.hourlyRows === 0 && diag?.catalogue !== undefined,
    { keys: Object.keys(diag ?? {}), audit: diag?.audit, hourly: diag?.hourlyRows },
  );
  const redaction = await rpc("kicklive_observability_explain", [`'user sent Authorization: Bearer abcdef.ghiJKLmnop to /x'`]);
  ok(
    "the redaction probe explains a refusal without storing the thing that caused it",
    redaction?.wouldStore === false && redaction?.preview === "[redacted]" && redaction?.reason === "BEARER_TOKEN",
    redaction,
  );
  const cleanText = await rpc("kicklive_observability_explain", [`'match 42 moved to second half'`]);
  ok("and lets an ordinary sentence through, which is how we know the rule is narrow", cleanText?.wouldStore === true && cleanText?.reason === null, cleanText);
  const quoteHeavy = await rpc("kicklive_observability_explain", [`'drop table activity_logs; -- it''s fine'`]);
  ok("the probe takes arbitrary text as data and answers about it, never running it", quoteHeavy?.inputLength > 10 && typeof quoteHeavy?.wouldStore === "boolean", quoteHeavy);

  await query("reset role");
  await query(`delete from public.metric_rollups where route = '/flow/:id'`).catch(() => {});
  await query(`delete from public.metric_daily where route = '/flow/:id'`).catch(() => {});
  await query(`delete from public.system_health where component = 'supabase' and reason = 'POOL_WAIT'`).catch(() => {});
  await query(`delete from public.activity_logs where action = 'flow.probe'`).catch(() => {});
  await asRole("service_role", ADMIN);
  log("      observability flow complete");
  return { failed };
}
